// =============================================================================
// Vivid Lingua — English track · Vocabulary deck
// -----------------------------------------------------------------------------
// A substantial, level-graded English vocabulary deck spanning CEFR A1..C2.
// It blends high-frequency everyday words with academic vocabulary that recurs
// on IELTS and SAT. Every entry carries an IPA transcription, part of speech, a
// learner-friendly definition, a natural example sentence, a CEFR level and a
// loose topical category for the trainer's filters. No duplicate headwords.
// =============================================================================

import { VocabWord } from '../types';

export const VOCAB: VocabWord[] = [
  // ----- A1 · everyday foundations ------------------------------------------
  {
    word: 'water',
    phonetic: '[ˈwɔːtə]',
    partOfSpeech: 'noun',
    definition: 'The clear liquid that falls as rain and that we drink to live.',
    example: 'Could I have a glass of water, please?',
    level: 'A1',
    category: 'Food & Drink',
  },
  {
    word: 'house',
    phonetic: '[haʊs]',
    partOfSpeech: 'noun',
    definition: 'A building where people live.',
    example: 'They bought a small house near the river.',
    level: 'A1',
    category: 'Home',
  },
  {
    word: 'friend',
    phonetic: '[frend]',
    partOfSpeech: 'noun',
    definition: 'A person you know well and like.',
    example: 'My best friend lives next door.',
    level: 'A1',
    category: 'People',
  },
  {
    word: 'happy',
    phonetic: '[ˈhæpi]',
    partOfSpeech: 'adjective',
    definition: 'Feeling pleased or glad.',
    example: 'She felt happy when she saw the good news.',
    level: 'A1',
    category: 'Emotions',
  },
  {
    word: 'eat',
    phonetic: '[iːt]',
    partOfSpeech: 'verb',
    definition: 'To put food in your mouth and swallow it.',
    example: 'We usually eat dinner at seven.',
    level: 'A1',
    category: 'Food & Drink',
  },
  {
    word: 'go',
    phonetic: '[ɡəʊ]',
    partOfSpeech: 'verb',
    definition: 'To move from one place to another.',
    example: 'I go to school by bus every morning.',
    level: 'A1',
    category: 'Movement',
  },
  {
    word: 'big',
    phonetic: '[bɪɡ]',
    partOfSpeech: 'adjective',
    definition: 'Large in size or amount.',
    example: 'They live in a big city.',
    level: 'A1',
    category: 'Description',
  },
  {
    word: 'school',
    phonetic: '[skuːl]',
    partOfSpeech: 'noun',
    definition: 'A place where children go to learn.',
    example: 'The children walk to school together.',
    level: 'A1',
    category: 'Education',
  },
  {
    word: 'day',
    phonetic: '[deɪ]',
    partOfSpeech: 'noun',
    definition: 'A period of 24 hours; the time when it is light.',
    example: 'It was a sunny day, so we went outside.',
    level: 'A1',
    category: 'Time',
  },
  {
    word: 'red',
    phonetic: '[red]',
    partOfSpeech: 'adjective',
    definition: 'Having the colour of blood or a ripe tomato.',
    example: 'She wore a bright red coat.',
    level: 'A1',
    category: 'Colours',
  },
  {
    word: 'work',
    phonetic: '[wɜːk]',
    partOfSpeech: 'verb',
    definition: 'To do a job to earn money or to make an effort.',
    example: 'My parents work in a hospital.',
    level: 'A1',
    category: 'Work',
  },
  {
    word: 'family',
    phonetic: '[ˈfæməli]',
    partOfSpeech: 'noun',
    definition: 'A group of people who are related to each other.',
    example: 'My whole family came to the party.',
    level: 'A1',
    category: 'People',
  },
  {
    word: 'morning',
    phonetic: '[ˈmɔːnɪŋ]',
    partOfSpeech: 'noun',
    definition: 'The early part of the day before noon.',
    example: 'I drink coffee every morning.',
    level: 'A1',
    category: 'Time',
  },
  {
    word: 'book',
    phonetic: '[bʊk]',
    partOfSpeech: 'noun',
    definition: 'A set of printed pages held together for reading.',
    example: 'He is reading an interesting book.',
    level: 'A1',
    category: 'Education',
  },
  {
    word: 'open',
    phonetic: '[ˈəʊpən]',
    partOfSpeech: 'verb',
    definition: 'To move something so that it is no longer closed.',
    example: 'Please open the window; it is hot in here.',
    level: 'A1',
    category: 'Daily Life',
  },
  {
    word: 'money',
    phonetic: '[ˈmʌni]',
    partOfSpeech: 'noun',
    definition: 'The coins and notes used to buy things.',
    example: 'I need to save money for the trip.',
    level: 'A1',
    category: 'Money',
  },
  {
    word: 'street',
    phonetic: '[striːt]',
    partOfSpeech: 'noun',
    definition: 'A road in a town or city with houses or shops.',
    example: 'They live on a quiet street.',
    level: 'A1',
    category: 'City',
  },
  {
    word: 'help',
    phonetic: '[help]',
    partOfSpeech: 'verb',
    definition: 'To make it easier for someone to do something.',
    example: 'Can you help me carry these bags?',
    level: 'A1',
    category: 'Daily Life',
  },
  {
    word: 'cold',
    phonetic: '[kəʊld]',
    partOfSpeech: 'adjective',
    definition: 'Having a low temperature; not warm.',
    example: 'It is very cold outside today.',
    level: 'A1',
    category: 'Nature',
  },
  {
    word: 'name',
    phonetic: '[neɪm]',
    partOfSpeech: 'noun',
    definition: 'The word people use to call a person or thing.',
    example: 'What is your name?',
    level: 'A1',
    category: 'People',
  },
  {
    word: 'buy',
    phonetic: '[baɪ]',
    partOfSpeech: 'verb',
    definition: 'To get something by paying money for it.',
    example: 'I want to buy some fruit at the market.',
    level: 'A1',
    category: 'Shopping',
  },
  {
    word: 'late',
    phonetic: '[leɪt]',
    partOfSpeech: 'adjective',
    definition: 'After the usual or expected time.',
    example: 'Sorry I am late; the bus was delayed.',
    level: 'A1',
    category: 'Time',
  },

  // ----- A2 · daily life and feelings ---------------------------------------
  {
    word: 'travel',
    phonetic: '[ˈtrævl]',
    partOfSpeech: 'verb',
    definition: 'To go from one place to another, usually far away.',
    example: 'They love to travel during the summer holidays.',
    level: 'A2',
    category: 'Travel',
  },
  {
    word: 'busy',
    phonetic: '[ˈbɪzi]',
    partOfSpeech: 'adjective',
    definition: 'Having a lot of things to do.',
    example: 'I am too busy to meet you today.',
    level: 'A2',
    category: 'Description',
  },
  {
    word: 'weather',
    phonetic: '[ˈweðə]',
    partOfSpeech: 'noun',
    definition: 'The state of the air, such as sun, rain or wind.',
    example: 'The weather was cold and windy yesterday.',
    level: 'A2',
    category: 'Nature',
  },
  {
    word: 'borrow',
    phonetic: '[ˈbɒrəʊ]',
    partOfSpeech: 'verb',
    definition: 'To take something for a short time and give it back later.',
    example: 'Can I borrow your pen for a minute?',
    level: 'A2',
    category: 'Daily Life',
  },
  {
    word: 'careful',
    phonetic: '[ˈkeəfl]',
    partOfSpeech: 'adjective',
    definition: 'Giving attention so that you do not make a mistake or get hurt.',
    example: 'Be careful when you cross the road.',
    level: 'A2',
    category: 'Description',
  },
  {
    word: 'invite',
    phonetic: '[ɪnˈvaɪt]',
    partOfSpeech: 'verb',
    definition: 'To ask someone to come to an event.',
    example: 'They invited us to their wedding.',
    level: 'A2',
    category: 'Social',
  },
  {
    word: 'expensive',
    phonetic: '[ɪkˈspensɪv]',
    partOfSpeech: 'adjective',
    definition: 'Costing a lot of money.',
    example: 'That restaurant is too expensive for me.',
    level: 'A2',
    category: 'Money',
  },
  {
    word: 'remember',
    phonetic: '[rɪˈmembə]',
    partOfSpeech: 'verb',
    definition: 'To keep something in your mind or bring it back to mind.',
    example: 'I cannot remember her phone number.',
    level: 'A2',
    category: 'Mind',
  },
  {
    word: 'neighbour',
    phonetic: '[ˈneɪbə]',
    partOfSpeech: 'noun',
    definition: 'A person who lives near you.',
    example: 'Our new neighbour is very friendly.',
    level: 'A2',
    category: 'People',
  },
  {
    word: 'healthy',
    phonetic: '[ˈhelθi]',
    partOfSpeech: 'adjective',
    definition: 'Good for your body; not ill.',
    example: 'Eating vegetables keeps you healthy.',
    level: 'A2',
    category: 'Health',
  },
  {
    word: 'arrive',
    phonetic: '[əˈraɪv]',
    partOfSpeech: 'verb',
    definition: 'To reach a place at the end of a journey.',
    example: 'The train will arrive at noon.',
    level: 'A2',
    category: 'Travel',
  },
  {
    word: 'quiet',
    phonetic: '[ˈkwaɪət]',
    partOfSpeech: 'adjective',
    definition: 'Making little or no noise.',
    example: 'Please be quiet in the library.',
    level: 'A2',
    category: 'Description',
  },
  {
    word: 'hobby',
    phonetic: '[ˈhɒbi]',
    partOfSpeech: 'noun',
    definition: 'An activity you enjoy doing in your free time.',
    example: 'Painting is her favourite hobby.',
    level: 'A2',
    category: 'Leisure',
  },
  {
    word: 'choose',
    phonetic: '[tʃuːz]',
    partOfSpeech: 'verb',
    definition: 'To decide which thing you want from a number of options.',
    example: 'You can choose any cake you like.',
    level: 'A2',
    category: 'Decisions',
  },
  {
    word: 'tired',
    phonetic: '[ˈtaɪəd]',
    partOfSpeech: 'adjective',
    definition: 'Needing rest or sleep.',
    example: 'I was very tired after the long walk.',
    level: 'A2',
    category: 'Emotions',
  },
  {
    word: 'enjoy',
    phonetic: '[ɪnˈdʒɔɪ]',
    partOfSpeech: 'verb',
    definition: 'To get pleasure from something.',
    example: 'We really enjoy walking by the sea.',
    level: 'A2',
    category: 'Leisure',
  },
  {
    word: 'difficult',
    phonetic: '[ˈdɪfɪkəlt]',
    partOfSpeech: 'adjective',
    definition: 'Not easy; needing effort or skill.',
    example: 'This exercise is more difficult than the last one.',
    level: 'A2',
    category: 'Description',
  },
  {
    word: 'discover',
    phonetic: '[dɪˈskʌvə]',
    partOfSpeech: 'verb',
    definition: 'To find something or learn about it for the first time.',
    example: 'We discovered a lovely beach near the town.',
    level: 'A2',
    category: 'Change',
  },
  {
    word: 'crowded',
    phonetic: '[ˈkraʊdɪd]',
    partOfSpeech: 'adjective',
    definition: 'Full of people or things, with little space.',
    example: 'The market was very crowded on Saturday.',
    level: 'A2',
    category: 'City',
  },
  {
    word: 'practise',
    phonetic: '[ˈpræktɪs]',
    partOfSpeech: 'verb',
    definition: 'To do something often so that you get better at it.',
    example: 'You should practise speaking every day.',
    level: 'A2',
    category: 'Education',
  },
  {
    word: 'comfortable',
    phonetic: '[ˈkʌmftəbl]',
    partOfSpeech: 'adjective',
    definition: 'Making you feel relaxed and free from pain.',
    example: 'These shoes are very comfortable for walking.',
    level: 'A2',
    category: 'Description',
  },
  {
    word: 'prepare',
    phonetic: '[prɪˈpeə]',
    partOfSpeech: 'verb',
    definition: 'To get something or yourself ready for use or for an event.',
    example: 'She prepared dinner for her guests.',
    level: 'A2',
    category: 'Daily Life',
  },
  {
    word: 'famous',
    phonetic: '[ˈfeɪməs]',
    partOfSpeech: 'adjective',
    definition: 'Known about by very many people.',
    example: 'The city is famous for its old buildings.',
    level: 'A2',
    category: 'Description',
  },

  // ----- B1 · intermediate, opinions and routines ---------------------------
  {
    word: 'achieve',
    phonetic: '[əˈtʃiːv]',
    partOfSpeech: 'verb',
    definition: 'To succeed in doing something after effort.',
    example: 'She worked hard to achieve her goals.',
    level: 'B1',
    category: 'Success',
  },
  {
    word: 'opinion',
    phonetic: '[əˈpɪnjən]',
    partOfSpeech: 'noun',
    definition: 'What you think or believe about something.',
    example: 'In my opinion, the film was too long.',
    level: 'B1',
    category: 'Communication',
  },
  {
    word: 'environment',
    phonetic: '[ɪnˈvaɪrənmənt]',
    partOfSpeech: 'noun',
    definition: 'The natural world of land, sea and air around us.',
    example: 'We must protect the environment from pollution.',
    level: 'B1',
    category: 'Nature',
  },
  {
    word: 'reduce',
    phonetic: '[rɪˈdjuːs]',
    partOfSpeech: 'verb',
    definition: 'To make something smaller in size, amount or number.',
    example: 'The shop reduced its prices last week.',
    level: 'B1',
    category: 'Change',
  },
  {
    word: 'advantage',
    phonetic: '[ədˈvɑːntɪdʒ]',
    partOfSpeech: 'noun',
    definition: 'Something that helps you or makes a situation better.',
    example: 'Speaking two languages is a real advantage.',
    level: 'B1',
    category: 'Benefits',
  },
  {
    word: 'suggest',
    phonetic: '[səˈdʒest]',
    partOfSpeech: 'verb',
    definition: 'To offer an idea or plan for others to think about.',
    example: 'I suggest we leave early to avoid traffic.',
    level: 'B1',
    category: 'Communication',
  },
  {
    word: 'experience',
    phonetic: '[ɪkˈspɪəriəns]',
    partOfSpeech: 'noun',
    definition: 'Knowledge or skill you get from doing something.',
    example: 'She has years of experience in teaching.',
    level: 'B1',
    category: 'Work',
  },
  {
    word: 'develop',
    phonetic: '[dɪˈveləp]',
    partOfSpeech: 'verb',
    definition: 'To grow or to make something grow or become more advanced.',
    example: 'The company plans to develop a new app.',
    level: 'B1',
    category: 'Change',
  },
  {
    word: 'familiar',
    phonetic: '[fəˈmɪliə]',
    partOfSpeech: 'adjective',
    definition: 'Well known to you because you have seen it before.',
    example: 'Her face looked familiar, but I forgot her name.',
    level: 'B1',
    category: 'Description',
  },
  {
    word: 'available',
    phonetic: '[əˈveɪləbl]',
    partOfSpeech: 'adjective',
    definition: 'Able to be used or obtained; free to be seen or talked to.',
    example: 'Tickets are still available for tonight.',
    level: 'B1',
    category: 'Description',
  },
  {
    word: 'encourage',
    phonetic: '[ɪnˈkʌrɪdʒ]',
    partOfSpeech: 'verb',
    definition: 'To give someone confidence or support to do something.',
    example: 'Good teachers encourage their students to ask questions.',
    level: 'B1',
    category: 'Communication',
  },
  {
    word: 'pollution',
    phonetic: '[pəˈluːʃn]',
    partOfSpeech: 'noun',
    definition: 'Harmful substances that make air, water or land dirty.',
    example: 'Air pollution is a serious problem in big cities.',
    level: 'B1',
    category: 'Nature',
  },
  {
    word: 'recommend',
    phonetic: '[ˌrekəˈmend]',
    partOfSpeech: 'verb',
    definition: 'To say that something is good and worth choosing.',
    example: 'Can you recommend a good hotel in town?',
    level: 'B1',
    category: 'Communication',
  },
  {
    word: 'responsible',
    phonetic: '[rɪˈspɒnsəbl]',
    partOfSpeech: 'adjective',
    definition: 'Having the duty to deal with something or care for someone.',
    example: 'She is responsible for the whole team.',
    level: 'B1',
    category: 'Work',
  },
  {
    word: 'improve',
    phonetic: '[ɪmˈpruːv]',
    partOfSpeech: 'verb',
    definition: 'To make something better or to become better.',
    example: 'Reading every day will improve your English.',
    level: 'B1',
    category: 'Change',
  },
  {
    word: 'modern',
    phonetic: '[ˈmɒdn]',
    partOfSpeech: 'adjective',
    definition: 'Belonging to the present time; using the newest ideas.',
    example: 'The museum has a modern glass entrance.',
    level: 'B1',
    category: 'Description',
  },
  {
    word: 'culture',
    phonetic: '[ˈkʌltʃə]',
    partOfSpeech: 'noun',
    definition: 'The way of life, ideas and customs of a group of people.',
    example: 'Travelling helps you understand other cultures.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'budget',
    phonetic: '[ˈbʌdʒɪt]',
    partOfSpeech: 'noun',
    definition: 'A plan of how much money you can spend.',
    example: 'We stayed within our budget for the holiday.',
    level: 'B1',
    category: 'Money',
  },
  {
    word: 'process',
    phonetic: '[ˈprəʊses]',
    partOfSpeech: 'noun',
    definition: 'A series of steps taken to achieve a particular result.',
    example: 'Learning a language is a slow process.',
    level: 'B1',
    category: 'Academic',
  },
  {
    word: 'efficient',
    phonetic: '[ɪˈfɪʃnt]',
    partOfSpeech: 'adjective',
    definition: 'Working well without wasting time, money or energy.',
    example: 'Public transport is an efficient way to travel.',
    level: 'B1',
    category: 'Description',
  },
  {
    word: 'global',
    phonetic: '[ˈɡləʊbl]',
    partOfSpeech: 'adjective',
    definition: 'Relating to the whole world.',
    example: 'Climate change is a global problem.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'survey',
    phonetic: '[ˈsɜːveɪ]',
    partOfSpeech: 'noun',
    definition: 'A set of questions used to collect people’s opinions.',
    example: 'A recent survey shows that most people walk to work.',
    level: 'B1',
    category: 'Research',
  },

  // ----- B2 · upper-intermediate, abstract ideas ----------------------------
  {
    word: 'consequence',
    phonetic: '[ˈkɒnsɪkwəns]',
    partOfSpeech: 'noun',
    definition: 'A result or effect of an action or situation.',
    example: 'He had to face the consequences of his decision.',
    level: 'B2',
    category: 'Cause & Effect',
  },
  {
    word: 'significant',
    phonetic: '[sɪɡˈnɪfɪkənt]',
    partOfSpeech: 'adjective',
    definition: 'Large or important enough to be noticed or have an effect.',
    example: 'There was a significant rise in sales this year.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'establish',
    phonetic: '[ɪˈstæblɪʃ]',
    partOfSpeech: 'verb',
    definition: 'To start or create something that is meant to last.',
    example: 'The charity was established over fifty years ago.',
    level: 'B2',
    category: 'Business',
  },
  {
    word: 'reluctant',
    phonetic: '[rɪˈlʌktənt]',
    partOfSpeech: 'adjective',
    definition: 'Not willing to do something and therefore slow to act.',
    example: 'She was reluctant to share her plans with us.',
    level: 'B2',
    category: 'Attitude',
  },
  {
    word: 'emphasise',
    phonetic: '[ˈemfəsaɪz]',
    partOfSpeech: 'verb',
    definition: 'To give special importance or attention to something.',
    example: 'The teacher emphasised the need for revision.',
    level: 'B2',
    category: 'Communication',
  },
  {
    word: 'inevitable',
    phonetic: '[ɪnˈevɪtəbl]',
    partOfSpeech: 'adjective',
    definition: 'Certain to happen and impossible to avoid.',
    example: 'With such poor planning, failure was inevitable.',
    level: 'B2',
    category: 'Certainty',
  },
  {
    word: 'maintain',
    phonetic: '[meɪnˈteɪn]',
    partOfSpeech: 'verb',
    definition: 'To keep something at the same level or in good condition.',
    example: 'It is hard to maintain a healthy diet while travelling.',
    level: 'B2',
    category: 'Change',
  },
  {
    word: 'controversial',
    phonetic: '[ˌkɒntrəˈvɜːʃl]',
    partOfSpeech: 'adjective',
    definition: 'Causing strong disagreement or public discussion.',
    example: 'The new law proved highly controversial.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'demonstrate',
    phonetic: '[ˈdemənstreɪt]',
    partOfSpeech: 'verb',
    definition: 'To show clearly that something is true or how it works.',
    example: 'The results demonstrate the value of regular exercise.',
    level: 'B2',
    category: 'Academic',
  },
  {
    word: 'sufficient',
    phonetic: '[səˈfɪʃnt]',
    partOfSpeech: 'adjective',
    definition: 'As much as is needed; enough.',
    example: 'We did not have sufficient time to finish the test.',
    level: 'B2',
    category: 'Quantity',
  },
  {
    word: 'perceive',
    phonetic: '[pəˈsiːv]',
    partOfSpeech: 'verb',
    definition: 'To notice or understand something in a particular way.',
    example: 'Many people perceive the change as a threat.',
    level: 'B2',
    category: 'Mind',
  },
  {
    word: 'beneficial',
    phonetic: '[ˌbenɪˈfɪʃl]',
    partOfSpeech: 'adjective',
    definition: 'Having a good or helpful effect.',
    example: 'Regular sleep is beneficial to your memory.',
    level: 'B2',
    category: 'Benefits',
  },
  {
    word: 'tendency',
    phonetic: '[ˈtendənsi]',
    partOfSpeech: 'noun',
    definition: 'A way someone or something usually behaves or develops.',
    example: 'He has a tendency to interrupt other people.',
    level: 'B2',
    category: 'Behaviour',
  },
  {
    word: 'distinguish',
    phonetic: '[dɪˈstɪŋɡwɪʃ]',
    partOfSpeech: 'verb',
    definition: 'To recognise the difference between two or more things.',
    example: 'Children learn to distinguish colours very early.',
    level: 'B2',
    category: 'Academic',
  },
  {
    word: 'reliable',
    phonetic: '[rɪˈlaɪəbl]',
    partOfSpeech: 'adjective',
    definition: 'Able to be trusted to do what is expected.',
    example: 'We need a reliable source for these figures.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'overcome',
    phonetic: '[ˌəʊvəˈkʌm]',
    partOfSpeech: 'verb',
    definition: 'To successfully deal with a problem or difficulty.',
    example: 'She overcame her fear of speaking in public.',
    level: 'B2',
    category: 'Success',
  },
  {
    word: 'apparent',
    phonetic: '[əˈpærənt]',
    partOfSpeech: 'adjective',
    definition: 'Easy to see or understand; clear.',
    example: 'It soon became apparent that the plan would fail.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'allocate',
    phonetic: '[ˈæləkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To give a share of something for a particular purpose.',
    example: 'The council allocated funds for new parks.',
    level: 'B2',
    category: 'Business',
  },
  {
    word: 'feasible',
    phonetic: '[ˈfiːzəbl]',
    partOfSpeech: 'adjective',
    definition: 'Possible to do easily or conveniently.',
    example: 'Is it feasible to finish the project this month?',
    level: 'B2',
    category: 'Reasoning',
  },
  {
    word: 'incentive',
    phonetic: '[ɪnˈsentɪv]',
    partOfSpeech: 'noun',
    definition: 'Something that encourages you to do something.',
    example: 'Lower taxes are an incentive to start a business.',
    level: 'B2',
    category: 'Economics',
  },
  {
    word: 'phenomenon',
    phonetic: '[fəˈnɒmɪnən]',
    partOfSpeech: 'noun',
    definition: 'Something that happens or exists, especially something studied.',
    example: 'Global warming is a worldwide phenomenon.',
    level: 'B2',
    category: 'Science',
  },
  {
    word: 'estimate',
    phonetic: '[ˈestɪmət]',
    partOfSpeech: 'noun',
    definition: 'A rough calculation of a number, amount or value.',
    example: 'Experts gave an estimate of two million visitors.',
    level: 'B2',
    category: 'Mathematics',
  },
  {
    word: 'fluctuate',
    phonetic: '[ˈflʌktʃueɪt]',
    partOfSpeech: 'verb',
    definition: 'To change often, especially up and down in level.',
    example: 'Prices tend to fluctuate during the year.',
    level: 'B2',
    category: 'Economics',
  },
  {
    word: 'subsequent',
    phonetic: '[ˈsʌbsɪkwənt]',
    partOfSpeech: 'adjective',
    definition: 'Happening after something else.',
    example: 'The first test failed, but subsequent ones succeeded.',
    level: 'B2',
    category: 'Time',
  },
  {
    word: 'integral',
    phonetic: '[ˈɪntɪɡrəl]',
    partOfSpeech: 'adjective',
    definition: 'Necessary and important as a part of a whole.',
    example: 'Teamwork is integral to the company’s success.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'diverse',
    phonetic: '[daɪˈvɜːs]',
    partOfSpeech: 'adjective',
    definition: 'Including many different types of people or things.',
    example: 'The city has a diverse and lively population.',
    level: 'B2',
    category: 'Society',
  },

  // ----- C1 · advanced academic and IELTS/SAT range -------------------------
  {
    word: 'comprehensive',
    phonetic: '[ˌkɒmprɪˈhensɪv]',
    partOfSpeech: 'adjective',
    definition: 'Including everything that is needed; complete and thorough.',
    example: 'The report gives a comprehensive overview of the market.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'advocate',
    phonetic: '[ˈædvəkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To publicly support a particular idea or way of doing things.',
    example: 'Many scientists advocate stronger climate policies.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'implication',
    phonetic: '[ˌɪmplɪˈkeɪʃn]',
    partOfSpeech: 'noun',
    definition: 'A likely result or effect that is not stated directly.',
    example: 'The study has important implications for public health.',
    level: 'C1',
    category: 'Cause & Effect',
  },
  {
    word: 'undermine',
    phonetic: '[ˌʌndəˈmaɪn]',
    partOfSpeech: 'verb',
    definition: 'To gradually weaken something or make it less effective.',
    example: 'Constant criticism can undermine a child’s confidence.',
    level: 'C1',
    category: 'Change',
  },
  {
    word: 'prevalent',
    phonetic: '[ˈprevələnt]',
    partOfSpeech: 'adjective',
    definition: 'Common or widespread in a particular place or time.',
    example: 'Smartphones are prevalent among teenagers today.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'coherent',
    phonetic: '[kəʊˈhɪərənt]',
    partOfSpeech: 'adjective',
    definition: 'Clear, logical and well organised; easy to follow.',
    example: 'A high band score requires a coherent argument.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'mitigate',
    phonetic: '[ˈmɪtɪɡeɪt]',
    partOfSpeech: 'verb',
    definition: 'To make something harmful or unpleasant less severe.',
    example: 'Planting trees can help mitigate the effects of heat.',
    level: 'C1',
    category: 'Solutions',
  },
  {
    word: 'substantial',
    phonetic: '[səbˈstænʃl]',
    partOfSpeech: 'adjective',
    definition: 'Large in amount, value or importance.',
    example: 'The project received substantial government funding.',
    level: 'C1',
    category: 'Quantity',
  },
  {
    word: 'undertake',
    phonetic: '[ˌʌndəˈteɪk]',
    partOfSpeech: 'verb',
    definition: 'To agree to do and begin a task or piece of work.',
    example: 'The institute undertook a major study of city traffic.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'arbitrary',
    phonetic: '[ˈɑːbɪtrəri]',
    partOfSpeech: 'adjective',
    definition: 'Based on chance or personal choice rather than reason.',
    example: 'The selection of winners seemed completely arbitrary.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'compelling',
    phonetic: '[kəmˈpelɪŋ]',
    partOfSpeech: 'adjective',
    definition: 'So strong or interesting that it convinces you.',
    example: 'She presented a compelling case for reform.',
    level: 'C1',
    category: 'Persuasion',
  },
  {
    word: 'derive',
    phonetic: '[dɪˈraɪv]',
    partOfSpeech: 'verb',
    definition: 'To get or obtain something from a source.',
    example: 'Many medicines are derived from plants.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'notwithstanding',
    phonetic: '[ˌnɒtwɪθˈstændɪŋ]',
    partOfSpeech: 'preposition',
    definition: 'In spite of; without being prevented by something.',
    example: 'Notwithstanding the rain, the festival went ahead.',
    level: 'C1',
    category: 'Connectors',
  },
  {
    word: 'discrepancy',
    phonetic: '[dɪsˈkrepənsi]',
    partOfSpeech: 'noun',
    definition: 'A difference between two things that should match.',
    example: 'There was a discrepancy between the two reports.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'pragmatic',
    phonetic: '[præɡˈmætɪk]',
    partOfSpeech: 'adjective',
    definition: 'Dealing with problems in a practical, sensible way.',
    example: 'We need a pragmatic solution, not a perfect one.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'consensus',
    phonetic: '[kənˈsensəs]',
    partOfSpeech: 'noun',
    definition: 'General agreement among a group of people.',
    example: 'There is a growing consensus on climate change.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'scrutinise',
    phonetic: '[ˈskruːtɪnaɪz]',
    partOfSpeech: 'verb',
    definition: 'To examine something very carefully and in detail.',
    example: 'Examiners scrutinise every claim in your essay.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'unprecedented',
    phonetic: '[ʌnˈpresɪdentɪd]',
    partOfSpeech: 'adjective',
    definition: 'Never having happened or existed before.',
    example: 'The city saw an unprecedented level of investment.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'attribute',
    phonetic: '[əˈtrɪbjuːt]',
    partOfSpeech: 'verb',
    definition: 'To say that something is caused by a particular thing.',
    example: 'She attributes her success to hard work.',
    level: 'C1',
    category: 'Cause & Effect',
  },
  {
    word: 'rhetoric',
    phonetic: '[ˈretərɪk]',
    partOfSpeech: 'noun',
    definition: 'The art of using language to persuade or impress people.',
    example: 'The speech was full of clever rhetoric.',
    level: 'C1',
    category: 'Language',
  },
  {
    word: 'empirical',
    phonetic: '[ɪmˈpɪrɪkl]',
    partOfSpeech: 'adjective',
    definition: 'Based on observation or experiment rather than theory.',
    example: 'There is little empirical evidence for the claim.',
    level: 'C1',
    category: 'Science',
  },
  {
    word: 'inherent',
    phonetic: '[ɪnˈhɪərənt]',
    partOfSpeech: 'adjective',
    definition: 'Existing as a natural and permanent part of something.',
    example: 'There are inherent risks in any investment.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'plausible',
    phonetic: '[ˈplɔːzəbl]',
    partOfSpeech: 'adjective',
    definition: 'Seeming reasonable or likely to be true.',
    example: 'He gave a plausible excuse for being late.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'aggregate',
    phonetic: '[ˈæɡrɪɡət]',
    partOfSpeech: 'noun',
    definition: 'A total formed by adding several amounts together.',
    example: 'The aggregate of all the scores was surprisingly high.',
    level: 'C1',
    category: 'Mathematics',
  },
  {
    word: 'cumulative',
    phonetic: '[ˈkjuːmjələtɪv]',
    partOfSpeech: 'adjective',
    definition: 'Increasing gradually as more is added.',
    example: 'The cumulative effect of small savings is large.',
    level: 'C1',
    category: 'Mathematics',
  },
  {
    word: 'concur',
    phonetic: '[kənˈkɜː]',
    partOfSpeech: 'verb',
    definition: 'To agree with someone or with an opinion.',
    example: 'Most researchers concur with these findings.',
    level: 'C1',
    category: 'Academic',
  },
  {
    word: 'paramount',
    phonetic: '[ˈpærəmaʊnt]',
    partOfSpeech: 'adjective',
    definition: 'More important than anything else.',
    example: 'Safety is of paramount importance in this lab.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'anomaly',
    phonetic: '[əˈnɒməli]',
    partOfSpeech: 'noun',
    definition: 'Something that differs from what is normal or expected.',
    example: 'The data showed one strange anomaly.',
    level: 'C1',
    category: 'Science',
  },

  // ----- C2 · proficiency, nuanced and literary -----------------------------
  {
    word: 'ubiquitous',
    phonetic: '[juːˈbɪkwɪtəs]',
    partOfSpeech: 'adjective',
    definition: 'Seeming to be present everywhere at the same time.',
    example: 'Mobile phones have become ubiquitous in modern life.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'meticulous',
    phonetic: '[məˈtɪkjələs]',
    partOfSpeech: 'adjective',
    definition: 'Showing great care and attention to small details.',
    example: 'The author is meticulous about historical accuracy.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'ameliorate',
    phonetic: '[əˈmiːliəreɪt]',
    partOfSpeech: 'verb',
    definition: 'To make a bad or unsatisfactory situation better.',
    example: 'New policies were introduced to ameliorate poverty.',
    level: 'C2',
    category: 'Solutions',
  },
  {
    word: 'nuance',
    phonetic: '[ˈnjuːɑːns]',
    partOfSpeech: 'noun',
    definition: 'A very small difference in meaning, feeling or sound.',
    example: 'A good translator captures every nuance of the text.',
    level: 'C2',
    category: 'Language',
  },
  {
    word: 'paradigm',
    phonetic: '[ˈpærədaɪm]',
    partOfSpeech: 'noun',
    definition: 'A typical model or pattern of how something works or is understood.',
    example: 'The discovery created a new paradigm in physics.',
    level: 'C2',
    category: 'Academic',
  },
  {
    word: 'esoteric',
    phonetic: '[ˌiːsəˈterɪk]',
    partOfSpeech: 'adjective',
    definition: 'Understood by only a small group with special knowledge.',
    example: 'The lecture was full of esoteric mathematical terms.',
    level: 'C2',
    category: 'Academic',
  },
  {
    word: 'juxtapose',
    phonetic: '[ˈdʒʌkstəpəʊz]',
    partOfSpeech: 'verb',
    definition: 'To place things side by side to show a contrast.',
    example: 'The film juxtaposes wealth and poverty in the same street.',
    level: 'C2',
    category: 'Literature',
  },
  {
    word: 'ephemeral',
    phonetic: '[ɪˈfemərəl]',
    partOfSpeech: 'adjective',
    definition: 'Lasting for a very short time.',
    example: 'Fame can be ephemeral and quickly forgotten.',
    level: 'C2',
    category: 'Time',
  },
  {
    word: 'cogent',
    phonetic: '[ˈkəʊdʒənt]',
    partOfSpeech: 'adjective',
    definition: 'Clear, logical and convincing.',
    example: 'She gave a cogent explanation of the results.',
    level: 'C2',
    category: 'Persuasion',
  },
  {
    word: 'quintessential',
    phonetic: '[ˌkwɪntɪˈsenʃl]',
    partOfSpeech: 'adjective',
    definition: 'Being the most perfect or typical example of something.',
    example: 'The café is the quintessential Parisian experience.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'innocuous',
    phonetic: '[ɪˈnɒkjuəs]',
    partOfSpeech: 'adjective',
    definition: 'Not harmful or offensive in any way.',
    example: 'What seemed an innocuous remark caused real offence.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'proliferate',
    phonetic: '[prəˈlɪfəreɪt]',
    partOfSpeech: 'verb',
    definition: 'To increase quickly in number and spread widely.',
    example: 'Streaming services have proliferated in recent years.',
    level: 'C2',
    category: 'Change',
  },
  {
    word: 'tenuous',
    phonetic: '[ˈtenjuəs]',
    partOfSpeech: 'adjective',
    definition: 'Very weak or slight; not strongly supported.',
    example: 'The link between the two events is tenuous at best.',
    level: 'C2',
    category: 'Reasoning',
  },
  {
    word: 'salient',
    phonetic: '[ˈseɪliənt]',
    partOfSpeech: 'adjective',
    definition: 'Most noticeable or important.',
    example: 'The report lists the salient points on one page.',
    level: 'C2',
    category: 'Academic',
  },
  {
    word: 'eloquent',
    phonetic: '[ˈeləkwənt]',
    partOfSpeech: 'adjective',
    definition: 'Able to express ideas clearly and in a powerful way.',
    example: 'She gave an eloquent speech at the ceremony.',
    level: 'C2',
    category: 'Language',
  },
  {
    word: 'dichotomy',
    phonetic: '[daɪˈkɒtəmi]',
    partOfSpeech: 'noun',
    definition: 'A division into two opposite or very different parts.',
    example: 'The essay explores the dichotomy between work and rest.',
    level: 'C2',
    category: 'Academic',
  },
  {
    word: 'austere',
    phonetic: '[ɒˈstɪə]',
    partOfSpeech: 'adjective',
    definition: 'Very plain and simple, with no decoration or comfort.',
    example: 'The monastery had an austere stone interior.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'placate',
    phonetic: '[pləˈkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To make someone less angry by doing or saying something.',
    example: 'The manager tried to placate the unhappy customers.',
    level: 'C2',
    category: 'Communication',
  },
  {
    word: 'verisimilitude',
    phonetic: '[ˌverɪsɪˈmɪlɪtjuːd]',
    partOfSpeech: 'noun',
    definition: 'The quality of seeming real or true.',
    example: 'The novel’s detail gives it great verisimilitude.',
    level: 'C2',
    category: 'Literature',
  },
  {
    word: 'sycophant',
    phonetic: '[ˈsɪkəfænt]',
    partOfSpeech: 'noun',
    definition: 'A person who praises powerful people to gain advantage.',
    example: 'The king was surrounded by sycophants.',
    level: 'C2',
    category: 'People',
  },
];
