// =============================================================================
// SAT — high-frequency vocabulary deck (with Mongolian glosses).
// -----------------------------------------------------------------------------
// A curated set of words that recur on the Digital SAT Reading & Writing
// section — especially "words in context" and "transitions" questions —
// spanning CEFR B1..C2. Each entry carries an IPA transcription, part of speech,
// an English definition, an accurate MONGOLIAN translation, a natural example
// sentence, a CEFR level and a topical category. No duplicate headwords.
// Conforms exactly to ExamVocab in ../types.
// =============================================================================
import { ExamVocab } from '../types';

export const SAT_VOCAB: ExamVocab[] = [
  // ----- B1 · accessible high-frequency words -------------------------------
  {
    word: 'analyze',
    phonetic: '[ˈænəlaɪz]',
    partOfSpeech: 'verb',
    definition: 'To examine something carefully in order to understand it.',
    mongolian: 'задлан шинжлэх, дүгнэх',
    example: 'Scientists analyze data before drawing any conclusions.',
    level: 'B1',
    category: 'Academic verbs',
  },
  {
    word: 'evidence',
    phonetic: '[ˈevɪdəns]',
    partOfSpeech: 'noun',
    definition: 'Facts or information that show whether something is true.',
    mongolian: 'нотолгоо, баримт',
    example: 'The lawyer presented strong evidence to support her case.',
    level: 'B1',
    category: 'Reasoning',
  },
  {
    word: 'claim',
    phonetic: '[kleɪm]',
    partOfSpeech: 'noun',
    definition: 'A statement that something is true, often without proof yet.',
    mongolian: 'мэдэгдэл, баталгаа',
    example: 'The author makes a bold claim in the opening paragraph.',
    level: 'B1',
    category: 'Reasoning',
  },
  {
    word: 'method',
    phonetic: '[ˈmeθəd]',
    partOfSpeech: 'noun',
    definition: 'A particular way of doing or achieving something.',
    mongolian: 'арга, аргачлал',
    example: 'Researchers used a new method to collect the samples.',
    level: 'B1',
    category: 'Academic nouns',
  },
  {
    word: 'effect',
    phonetic: '[ɪˈfekt]',
    partOfSpeech: 'noun',
    definition: 'A change that is the result of an action or cause.',
    mongolian: 'нөлөө, үр дагавар',
    example: 'The new policy had a positive effect on attendance.',
    level: 'B1',
    category: 'Cause and effect',
  },
  {
    word: 'increase',
    phonetic: '[ɪnˈkriːs]',
    partOfSpeech: 'verb',
    definition: 'To become or make something larger in amount or degree.',
    mongolian: 'нэмэгдэх, өсгөх',
    example: 'Sales increase sharply during the holiday season.',
    level: 'B1',
    category: 'Data and trends',
  },
  {
    word: 'similar',
    phonetic: '[ˈsɪmələ(r)]',
    partOfSpeech: 'adjective',
    definition: 'Almost the same as something else but not exactly.',
    mongolian: 'төстэй, ижил төрлийн',
    example: 'The two paintings use similar colors and shapes.',
    level: 'B1',
    category: 'Comparison',
  },
  {
    word: 'purpose',
    phonetic: '[ˈpɜːpəs]',
    partOfSpeech: 'noun',
    definition: 'The reason for which something is done or created.',
    mongolian: 'зорилго, учир',
    example: 'The purpose of the survey was to gather public opinion.',
    level: 'B1',
    category: 'Author intent',
  },
  {
    word: 'support',
    phonetic: '[səˈpɔːt]',
    partOfSpeech: 'verb',
    definition: 'To help show that something is true; to back up.',
    mongolian: 'дэмжих, нотлох',
    example: 'These results support the original hypothesis.',
    level: 'B1',
    category: 'Reasoning',
  },
  {
    word: 'suggest',
    phonetic: '[səˈdʒest]',
    partOfSpeech: 'verb',
    definition: 'To put forward an idea or imply something indirectly.',
    mongolian: 'санал болгох, илэрхийлэх',
    example: 'The data suggest that exercise improves memory.',
    level: 'B1',
    category: 'Reasoning',
  },
  {
    word: 'benefit',
    phonetic: '[ˈbenɪfɪt]',
    partOfSpeech: 'noun',
    definition: 'An advantage or helpful result of something.',
    mongolian: 'ашиг тус, давуу тал',
    example: 'One benefit of reading widely is a larger vocabulary.',
    level: 'B1',
    category: 'Academic nouns',
  },
  {
    word: 'specific',
    phonetic: '[spəˈsɪfɪk]',
    partOfSpeech: 'adjective',
    definition: 'Clearly defined or particular, not general.',
    mongolian: 'тодорхой, нарийн',
    example: 'Give a specific example to make your point clearer.',
    level: 'B1',
    category: 'Description',
  },

  // ----- B2 · core SAT range ------------------------------------------------
  {
    word: 'significant',
    phonetic: '[sɪɡˈnɪfɪkənt]',
    partOfSpeech: 'adjective',
    definition: 'Large or important enough to have an effect or be noticed.',
    mongolian: 'чухал, мэдэгдэхүйц',
    example: 'There was a significant rise in temperatures last decade.',
    level: 'B2',
    category: 'Data and trends',
  },
  {
    word: 'establish',
    phonetic: '[ɪˈstæblɪʃ]',
    partOfSpeech: 'verb',
    definition: 'To set up firmly or prove something to be true.',
    mongolian: 'тогтоох, бий болгох',
    example: 'The study helped establish a link between diet and health.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'demonstrate',
    phonetic: '[ˈdemənstreɪt]',
    partOfSpeech: 'verb',
    definition: 'To show clearly that something exists or is true.',
    mongolian: 'харуулах, нотлох',
    example: 'The experiment demonstrates how plants respond to light.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'consequently',
    phonetic: '[ˈkɒnsɪkwəntli]',
    partOfSpeech: 'adverb',
    definition: 'As a result; therefore.',
    mongolian: 'үүний улмаас, иймээс',
    example: 'It rained all week; consequently, the river overflowed.',
    level: 'B2',
    category: 'Transitions',
  },
  {
    word: 'nevertheless',
    phonetic: '[ˌnevəðəˈles]',
    partOfSpeech: 'adverb',
    definition: 'In spite of what has just been said; however.',
    mongolian: 'гэсэн хэдий ч, тэгсэн ч',
    example: 'The task was hard; nevertheless, she finished it on time.',
    level: 'B2',
    category: 'Transitions',
  },
  {
    word: 'furthermore',
    phonetic: '[ˌfɜːðəˈmɔː(r)]',
    partOfSpeech: 'adverb',
    definition: 'In addition; used to add a further point.',
    mongolian: 'түүнчлэн, мөн',
    example: 'The plan is cheap; furthermore, it is easy to carry out.',
    level: 'B2',
    category: 'Transitions',
  },
  {
    word: 'illustrate',
    phonetic: '[ˈɪləstreɪt]',
    partOfSpeech: 'verb',
    definition: 'To make something clear by giving an example.',
    mongolian: 'жишээгээр тайлбарлах',
    example: 'This case illustrates the danger of acting too quickly.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'contrast',
    phonetic: '[ˈkɒntrɑːst]',
    partOfSpeech: 'noun',
    definition: 'A clear difference between two things compared together.',
    mongolian: 'ялгаа, эсрэгцэл',
    example: 'There is a sharp contrast between the two writers’ styles.',
    level: 'B2',
    category: 'Comparison',
  },
  {
    word: 'emphasize',
    phonetic: '[ˈemfəsaɪz]',
    partOfSpeech: 'verb',
    definition: 'To give special importance or attention to something.',
    mongolian: 'онцлох, чухалчлах',
    example: 'The teacher emphasized the need for careful planning.',
    level: 'B2',
    category: 'Author intent',
  },
  {
    word: 'perspective',
    phonetic: '[pəˈspektɪv]',
    partOfSpeech: 'noun',
    definition: 'A particular way of thinking about or viewing something.',
    mongolian: 'үзэл бодол, өнцөг',
    example: 'The essay offers a fresh perspective on city life.',
    level: 'B2',
    category: 'Author intent',
  },
  {
    word: 'assumption',
    phonetic: '[əˈsʌmpʃn]',
    partOfSpeech: 'noun',
    definition: 'Something accepted as true without proof.',
    mongolian: 'таамаглал, урьдчилсан төсөөлөл',
    example: 'The argument rests on the assumption that prices will fall.',
    level: 'B2',
    category: 'Reasoning',
  },
  {
    word: 'conclude',
    phonetic: '[kənˈkluːd]',
    partOfSpeech: 'verb',
    definition: 'To decide something after considering the facts.',
    mongolian: 'дүгнэх, дүгнэлт хийх',
    example: 'From the data, we can conclude that the method works.',
    level: 'B2',
    category: 'Reasoning',
  },
  {
    word: 'reluctant',
    phonetic: '[rɪˈlʌktənt]',
    partOfSpeech: 'adjective',
    definition: 'Unwilling and hesitant to do something.',
    mongolian: 'дургүй, эргэлзсэн',
    example: 'He was reluctant to share his unfinished work.',
    level: 'B2',
    category: 'Character and tone',
  },
  {
    word: 'objective',
    phonetic: '[əbˈdʒektɪv]',
    partOfSpeech: 'adjective',
    definition: 'Based on facts rather than feelings or opinions.',
    mongolian: 'бодит, хувийн сэтгэгдэлгүй',
    example: 'A good report should be objective and balanced.',
    level: 'B2',
    category: 'Tone and style',
  },
  {
    word: 'subsequent',
    phonetic: '[ˈsʌbsɪkwənt]',
    partOfSpeech: 'adjective',
    definition: 'Coming after something else in time or order.',
    mongolian: 'дараагийн, удаах',
    example: 'The first test failed, but subsequent trials succeeded.',
    level: 'B2',
    category: 'Sequence',
  },
  {
    word: 'distinct',
    phonetic: '[dɪˈstɪŋkt]',
    partOfSpeech: 'adjective',
    definition: 'Clearly different or separate from others.',
    mongolian: 'тодорхой ялгаатай, өвөрмөц',
    example: 'Each region has a distinct dialect and tradition.',
    level: 'B2',
    category: 'Comparison',
  },
  {
    word: 'tendency',
    phonetic: '[ˈtendənsi]',
    partOfSpeech: 'noun',
    definition: 'A general way that something usually happens or behaves.',
    mongolian: 'хандлага, чиг хандлага',
    example: 'There is a tendency for prices to rise before holidays.',
    level: 'B2',
    category: 'Data and trends',
  },
  {
    word: 'restrict',
    phonetic: '[rɪˈstrɪkt]',
    partOfSpeech: 'verb',
    definition: 'To limit the size, amount, or range of something.',
    mongolian: 'хязгаарлах, хориглох',
    example: 'The rules restrict access to certain areas of the lab.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'consistent',
    phonetic: '[kənˈsɪstənt]',
    partOfSpeech: 'adjective',
    definition: 'Always behaving or happening in the same way.',
    mongolian: 'тогтвортой, нийцтэй',
    example: 'Her results were consistent across every experiment.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'derive',
    phonetic: '[dɪˈraɪv]',
    partOfSpeech: 'verb',
    definition: 'To obtain or develop something from a source.',
    mongolian: 'гаргаж авах, үүсэх',
    example: 'Many English words derive from Latin roots.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'novel',
    phonetic: '[ˈnɒvl]',
    partOfSpeech: 'adjective',
    definition: 'New and original; not done or seen before.',
    mongolian: 'шинэлэг, шинэ санаатай',
    example: 'The team proposed a novel approach to the old problem.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'crucial',
    phonetic: '[ˈkruːʃl]',
    partOfSpeech: 'adjective',
    definition: 'Extremely important because it affects the outcome.',
    mongolian: 'нэн чухал, шийдвэрлэх',
    example: 'Timing is crucial when launching a new product.',
    level: 'B2',
    category: 'Description',
  },
  {
    word: 'undermine',
    phonetic: '[ˌʌndəˈmaɪn]',
    partOfSpeech: 'verb',
    definition: 'To weaken something gradually or secretly.',
    mongolian: 'сулруулах, бялхуулах',
    example: 'Constant criticism can undermine a person’s confidence.',
    level: 'B2',
    category: 'Academic verbs',
  },
  {
    word: 'advocate',
    phonetic: '[ˈædvəkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To publicly support a particular idea or course of action.',
    mongolian: 'дэмжих, талд нь зогсох',
    example: 'The senator advocates stronger protections for forests.',
    level: 'B2',
    category: 'Argument',
  },

  // ----- C1 · advanced SAT range --------------------------------------------
  {
    word: 'ambiguous',
    phonetic: '[æmˈbɪɡjuəs]',
    partOfSpeech: 'adjective',
    definition: 'Having more than one possible meaning; unclear.',
    mongolian: 'хоёрдмол, ойлгомжгүй',
    example: 'The ending of the story is deliberately ambiguous.',
    level: 'C1',
    category: 'Tone and style',
  },
  {
    word: 'plausible',
    phonetic: '[ˈplɔːzəbl]',
    partOfSpeech: 'adjective',
    definition: 'Seeming reasonable or probably true.',
    mongolian: 'үнэмшилтэй, болмоор',
    example: 'She gave a plausible explanation for the delay.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'paradox',
    phonetic: '[ˈpærədɒks]',
    partOfSpeech: 'noun',
    definition: 'A statement that seems contradictory but may be true.',
    mongolian: 'парадокс, зөрчилт санаа',
    example: 'It is a paradox that the louder he spoke, the less he said.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'nuance',
    phonetic: '[ˈnjuːɑːns]',
    partOfSpeech: 'noun',
    definition: 'A very slight difference in meaning, feeling, or tone.',
    mongolian: 'нарийн ялгаа, өнгө аяс',
    example: 'A good translator captures the nuance of the original text.',
    level: 'C1',
    category: 'Tone and style',
  },
  {
    word: 'cursory',
    phonetic: '[ˈkɜːsəri]',
    partOfSpeech: 'adjective',
    definition: 'Done quickly and without attention to detail.',
    mongolian: 'хайхрамжгүй, өнгөц',
    example: 'A cursory glance at the data missed the key trend.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'scrutiny',
    phonetic: '[ˈskruːtəni]',
    partOfSpeech: 'noun',
    definition: 'Careful and critical examination of something.',
    mongolian: 'нарийвчилсан шалгалт, ажиглалт',
    example: 'The proposal did not hold up under close scrutiny.',
    level: 'C1',
    category: 'Academic nouns',
  },
  {
    word: 'mitigate',
    phonetic: '[ˈmɪtɪɡeɪt]',
    partOfSpeech: 'verb',
    definition: 'To make something less harmful, serious, or severe.',
    mongolian: 'зөөлрүүлэх, бууруулах',
    example: 'Planting trees can mitigate the effects of flooding.',
    level: 'C1',
    category: 'Academic verbs',
  },
  {
    word: 'arbitrary',
    phonetic: '[ˈɑːbɪtrəri]',
    partOfSpeech: 'adjective',
    definition: 'Based on chance or personal choice rather than reason.',
    mongolian: 'дур зоргын, дурын',
    example: 'The deadline felt arbitrary and was hard to justify.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'coherent',
    phonetic: '[kəʊˈhɪərənt]',
    partOfSpeech: 'adjective',
    definition: 'Logical, clear, and well organized.',
    mongolian: 'логиктой, уялдаа холбоотой',
    example: 'A coherent essay leads the reader smoothly from point to point.',
    level: 'C1',
    category: 'Tone and style',
  },
  {
    word: 'empirical',
    phonetic: '[ɪmˈpɪrɪkl]',
    partOfSpeech: 'adjective',
    definition: 'Based on observation or experiment, not theory alone.',
    mongolian: 'туршилтад тулгуурласан, эмпирик',
    example: 'The claim needs empirical evidence before it is accepted.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'inevitable',
    phonetic: '[ɪnˈevɪtəbl]',
    partOfSpeech: 'adjective',
    definition: 'Certain to happen and impossible to avoid.',
    mongolian: 'зайлшгүй тохиолдох, гарцаагүй',
    example: 'With so many warnings, the crash seemed almost inevitable.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'profound',
    phonetic: '[prəˈfaʊnd]',
    partOfSpeech: 'adjective',
    definition: 'Very great, deep, or strongly felt.',
    mongolian: 'гүн гүнзгий, нөлөө ихтэй',
    example: 'The discovery had a profound effect on modern medicine.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'paramount',
    phonetic: '[ˈpærəmaʊnt]',
    partOfSpeech: 'adjective',
    definition: 'More important than anything else; supreme.',
    mongolian: 'хамгийн чухал, дээд зэргийн',
    example: 'Safety is paramount when working in a chemistry lab.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'underscore',
    phonetic: '[ˌʌndəˈskɔː(r)]',
    partOfSpeech: 'verb',
    definition: 'To emphasize or draw attention to something.',
    mongolian: 'онцлох, тодотгох',
    example: 'The findings underscore the importance of regular testing.',
    level: 'C1',
    category: 'Author intent',
  },
  {
    word: 'compelling',
    phonetic: '[kəmˈpelɪŋ]',
    partOfSpeech: 'adjective',
    definition: 'So convincing or interesting that it holds attention.',
    mongolian: 'үнэмшилтэй, татах хүчтэй',
    example: 'She made a compelling case for funding the project.',
    level: 'C1',
    category: 'Argument',
  },
  {
    word: 'refute',
    phonetic: '[rɪˈfjuːt]',
    partOfSpeech: 'verb',
    definition: 'To prove that a statement or argument is wrong.',
    mongolian: 'няцаах, эсэргүүцэн няцаах',
    example: 'New data refute the earlier claim about the planet’s age.',
    level: 'C1',
    category: 'Argument',
  },
  {
    word: 'concede',
    phonetic: '[kənˈsiːd]',
    partOfSpeech: 'verb',
    definition: 'To admit that something is true, often unwillingly.',
    mongolian: 'хүлээн зөвшөөрөх, буулт хийх',
    example: 'Even critics concede that the design is elegant.',
    level: 'C1',
    category: 'Argument',
  },
  {
    word: 'prevalent',
    phonetic: '[ˈprevələnt]',
    partOfSpeech: 'adjective',
    definition: 'Common or widespread in a particular place or time.',
    mongolian: 'түгээмэл, өргөн тархсан',
    example: 'This belief was prevalent among scholars of the period.',
    level: 'C1',
    category: 'Data and trends',
  },
  {
    word: 'innovative',
    phonetic: '[ˈɪnəveɪtɪv]',
    partOfSpeech: 'adjective',
    definition: 'Introducing new ideas or original ways of doing things.',
    mongolian: 'шинэлэг, шинэчлэгч',
    example: 'The company is known for its innovative product designs.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'volatile',
    phonetic: '[ˈvɒlətaɪl]',
    partOfSpeech: 'adjective',
    definition: 'Likely to change suddenly and unpredictably.',
    mongolian: 'тогтворгүй, хувирамтгай',
    example: 'Stock prices were volatile throughout the crisis.',
    level: 'C1',
    category: 'Data and trends',
  },
  {
    word: 'comprehensive',
    phonetic: '[ˌkɒmprɪˈhensɪv]',
    partOfSpeech: 'adjective',
    definition: 'Complete and including everything that is needed.',
    mongolian: 'иж бүрэн, дэлгэрэнгүй',
    example: 'The report gives a comprehensive overview of the issue.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'inherent',
    phonetic: '[ɪnˈhɪərənt]',
    partOfSpeech: 'adjective',
    definition: 'Existing as a natural and permanent part of something.',
    mongolian: 'төрөлхийн, угийн салшгүй',
    example: 'There are inherent risks in any scientific experiment.',
    level: 'C1',
    category: 'Description',
  },
  {
    word: 'speculate',
    phonetic: '[ˈspekjuleɪt]',
    partOfSpeech: 'verb',
    definition: 'To form an opinion without firm evidence; to guess.',
    mongolian: 'таамаглах, эргэцүүлэх',
    example: 'Historians can only speculate about what was lost.',
    level: 'C1',
    category: 'Reasoning',
  },
  {
    word: 'rigorous',
    phonetic: '[ˈrɪɡərəs]',
    partOfSpeech: 'adjective',
    definition: 'Very careful, thorough, and exact.',
    mongolian: 'нягт нямбай, хатуу чанд',
    example: 'The claim survived a rigorous review by other scientists.',
    level: 'C1',
    category: 'Academic nouns',
  },
  {
    word: 'redundant',
    phonetic: '[rɪˈdʌndənt]',
    partOfSpeech: 'adjective',
    definition: 'Not needed because it repeats something already present.',
    mongolian: 'илүүц, давхардсан',
    example: 'The editor cut several redundant sentences from the draft.',
    level: 'C1',
    category: 'Tone and style',
  },
  {
    word: 'pragmatic',
    phonetic: '[præɡˈmætɪk]',
    partOfSpeech: 'adjective',
    definition: 'Dealing with problems in a practical, realistic way.',
    mongolian: 'практик, бодит арга барилтай',
    example: 'They took a pragmatic approach and fixed the worst issues first.',
    level: 'C1',
    category: 'Character and tone',
  },
  {
    word: 'ostensibly',
    phonetic: '[ɒˈstensəbli]',
    partOfSpeech: 'adverb',
    definition: 'Apparently or seemingly, though perhaps not really.',
    mongolian: 'гадна талаар, нэрнээс нь',
    example: 'He left early, ostensibly to catch a train.',
    level: 'C1',
    category: 'Tone and style',
  },

  // ----- C2 · the hardest SAT words -----------------------------------------
  {
    word: 'ubiquitous',
    phonetic: '[juːˈbɪkwɪtəs]',
    partOfSpeech: 'adjective',
    definition: 'Seeming to be present everywhere at the same time.',
    mongolian: 'хаа сайгүй буй, түгээмэл',
    example: 'Smartphones have become ubiquitous in daily life.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'meticulous',
    phonetic: '[məˈtɪkjələs]',
    partOfSpeech: 'adjective',
    definition: 'Extremely careful about small details.',
    mongolian: 'нягт нямбай, нарийн',
    example: 'Her meticulous notes made the experiment easy to repeat.',
    level: 'C2',
    category: 'Character and tone',
  },
  {
    word: 'enigmatic',
    phonetic: '[ˌenɪɡˈmætɪk]',
    partOfSpeech: 'adjective',
    definition: 'Mysterious and difficult to understand.',
    mongolian: 'нууцлаг, ойлгомжгүй',
    example: 'The poet’s enigmatic lines invite many interpretations.',
    level: 'C2',
    category: 'Tone and style',
  },
  {
    word: 'tenuous',
    phonetic: '[ˈtenjuəs]',
    partOfSpeech: 'adjective',
    definition: 'Very weak or slight; not strongly supported.',
    mongolian: 'сул дорой, нимгэн',
    example: 'The connection between the two events is tenuous at best.',
    level: 'C2',
    category: 'Argument',
  },
  {
    word: 'austere',
    phonetic: '[ɔːˈstɪə(r)]',
    partOfSpeech: 'adjective',
    definition: 'Plain and without decoration; severe or strict.',
    mongolian: 'хатуу ширүүн, чимэглэлгүй',
    example: 'The monastery’s austere rooms held only a bed and a desk.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'pervasive',
    phonetic: '[pəˈveɪsɪv]',
    partOfSpeech: 'adjective',
    definition: 'Spreading widely and present throughout something.',
    mongolian: 'нэвт шингэсэн, өргөн тархсан',
    example: 'A pervasive sense of unease ran through the whole novel.',
    level: 'C2',
    category: 'Tone and style',
  },
  {
    word: 'cogent',
    phonetic: '[ˈkəʊdʒənt]',
    partOfSpeech: 'adjective',
    definition: 'Clear, logical, and convincing.',
    mongolian: 'үнэмшилтэй, логиктой',
    example: 'She offered a cogent argument that no one could rebut.',
    level: 'C2',
    category: 'Argument',
  },
  {
    word: 'innocuous',
    phonetic: '[ɪˈnɒkjuəs]',
    partOfSpeech: 'adjective',
    definition: 'Not harmful or offensive; harmless.',
    mongolian: 'хор хөнөөлгүй, аюулгүй',
    example: 'What seemed an innocuous remark deeply upset her.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'juxtapose',
    phonetic: '[ˌdʒʌkstəˈpəʊz]',
    partOfSpeech: 'verb',
    definition: 'To place two things side by side to compare or contrast them.',
    mongolian: 'зэрэгцүүлэн тавих, харьцуулах',
    example: 'The film juxtaposes scenes of wealth and poverty.',
    level: 'C2',
    category: 'Tone and style',
  },
  {
    word: 'paradigm',
    phonetic: '[ˈpærədaɪm]',
    partOfSpeech: 'noun',
    definition: 'A typical example or model of how something works.',
    mongolian: 'үлгэр загвар, парадигм',
    example: 'The discovery created a new paradigm in physics.',
    level: 'C2',
    category: 'Academic nouns',
  },
  {
    word: 'esoteric',
    phonetic: '[ˌesəˈterɪk]',
    partOfSpeech: 'adjective',
    definition: 'Understood by only a small group with special knowledge.',
    mongolian: 'нарийн мэргэжлийн, цөөнд ойлгогдох',
    example: 'The lecture was too esoteric for a general audience.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'quintessential',
    phonetic: '[ˌkwɪntɪˈsenʃl]',
    partOfSpeech: 'adjective',
    definition: 'Representing the most perfect example of something.',
    mongolian: 'жинхэнэ төлөөлөл, тон төгс жишээ',
    example: 'The café is the quintessential meeting place of the town.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'recalcitrant',
    phonetic: '[rɪˈkælsɪtrənt]',
    partOfSpeech: 'adjective',
    definition: 'Stubbornly refusing to obey or cooperate.',
    mongolian: 'дуулгаваргүй, зөрүүд',
    example: 'The recalcitrant student ignored every warning.',
    level: 'C2',
    category: 'Character and tone',
  },
  {
    word: 'ephemeral',
    phonetic: '[ɪˈfemərəl]',
    partOfSpeech: 'adjective',
    definition: 'Lasting for a very short time.',
    mongolian: 'түр зуурын, богино настай',
    example: 'Fame can be ephemeral, fading as quickly as it arrives.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'superfluous',
    phonetic: '[suːˈpɜːfluəs]',
    partOfSpeech: 'adjective',
    definition: 'More than is needed; unnecessary.',
    mongolian: 'илүүдэл, хэрэгцээгүй',
    example: 'The editor removed every superfluous adjective.',
    level: 'C2',
    category: 'Tone and style',
  },
  {
    word: 'idiosyncratic',
    phonetic: '[ˌɪdiəsɪŋˈkrætɪk]',
    partOfSpeech: 'adjective',
    definition: 'Peculiar to one individual; distinctly unusual.',
    mongolian: 'өвөрмөц онцлогтой, хувийн содон',
    example: 'His idiosyncratic style is impossible to imitate.',
    level: 'C2',
    category: 'Character and tone',
  },
  {
    word: 'antithetical',
    phonetic: '[ˌæntɪˈθetɪkl]',
    partOfSpeech: 'adjective',
    definition: 'Directly opposed or contrasting in nature.',
    mongolian: 'эсрэг тэсрэг, бүрэн зөрчилтэй',
    example: 'Greed is antithetical to the group’s stated values.',
    level: 'C2',
    category: 'Argument',
  },
  {
    word: 'salient',
    phonetic: '[ˈseɪliənt]',
    partOfSpeech: 'adjective',
    definition: 'Most noticeable or important; standing out.',
    mongolian: 'тод томруун, гол онцлох',
    example: 'The report lists the most salient points on page one.',
    level: 'C2',
    category: 'Author intent',
  },
  {
    word: 'disparate',
    phonetic: '[ˈdɪspərət]',
    partOfSpeech: 'adjective',
    definition: 'Very different in kind; not able to be compared easily.',
    mongolian: 'эрс ялгаатай, хоорондоо нийцэхгүй',
    example: 'The essay weaves together disparate ideas into one theme.',
    level: 'C2',
    category: 'Comparison',
  },
  {
    word: 'pernicious',
    phonetic: '[pəˈnɪʃəs]',
    partOfSpeech: 'adjective',
    definition: 'Having a harmful effect, especially in a gradual way.',
    mongolian: 'аажмаар хор хөнөөлтэй, гэмтээх',
    example: 'The rumor had a pernicious effect on her reputation.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'laconic',
    phonetic: '[ləˈkɒnɪk]',
    partOfSpeech: 'adjective',
    definition: 'Using very few words; concise to the point of being terse.',
    mongolian: 'товч тодорхой, цөөн үгтэй',
    example: 'His laconic reply told us he was unimpressed.',
    level: 'C2',
    category: 'Tone and style',
  },
  {
    word: 'tangential',
    phonetic: '[tænˈdʒenʃl]',
    partOfSpeech: 'adjective',
    definition: 'Only slightly related to the main subject.',
    mongolian: 'гол сэдэвтэй сул холбоотой, хажуугийн',
    example: 'The speaker kept drifting into tangential anecdotes.',
    level: 'C2',
    category: 'Argument',
  },
  {
    word: 'sanguine',
    phonetic: '[ˈsæŋɡwɪn]',
    partOfSpeech: 'adjective',
    definition: 'Optimistic or positive, especially in a difficult situation.',
    mongolian: 'өөдрөг, найдвар дүүрэн',
    example: 'Despite the setbacks, the founders remained sanguine.',
    level: 'C2',
    category: 'Character and tone',
  },
  {
    word: 'incongruous',
    phonetic: '[ɪnˈkɒŋɡruəs]',
    partOfSpeech: 'adjective',
    definition: 'Out of place; not in harmony with its surroundings.',
    mongolian: 'үл нийцэх, зохисгүй',
    example: 'The modern tower looked incongruous beside the old church.',
    level: 'C2',
    category: 'Description',
  },
  {
    word: 'venerable',
    phonetic: '[ˈvenərəbl]',
    partOfSpeech: 'adjective',
    definition: 'Respected because of great age, wisdom, or character.',
    mongolian: 'хүндэтгэл хүлээсэн, нэр хүндтэй',
    example: 'The venerable professor had taught for fifty years.',
    level: 'C2',
    category: 'Character and tone',
  },
  {
    word: 'gregarious',
    phonetic: '[ɡrɪˈɡeəriəs]',
    partOfSpeech: 'adjective',
    definition: 'Fond of company; sociable.',
    mongolian: 'нийтэч, нөхөрсөг',
    example: 'Her gregarious nature made the whole team feel welcome.',
    level: 'C2',
    category: 'Character and tone',
  },
];
