// =============================================================================
// IELTS — academic vocabulary deck (with Mongolian glosses).
// -----------------------------------------------------------------------------
// A curated set of words that recur across IELTS Reading, Listening, Writing and
// Speaking, spanning CEFR A2..C2. Each entry carries an IPA transcription, part
// of speech, an English definition, an accurate MONGOLIAN translation, a natural
// example sentence, a CEFR level and an exam-domain category. No duplicate
// headwords. Conforms exactly to ExamVocab in ../types.
// =============================================================================
import { ExamVocab } from '../types';
import { IELTS_VOCAB_GENERATED } from './ieltsVocabGenerated';

const IELTS_VOCAB_CURATED: ExamVocab[] = [
  // ----- A2 · everyday academic foundations ---------------------------------
  {
    word: 'improve',
    phonetic: '[ɪmˈpruːv]',
    partOfSpeech: 'verb',
    definition: 'To make something better, or to become better.',
    mongolian: 'сайжруулах, дээшлүүлэх',
    example: 'Reading every day will improve your vocabulary.',
    level: 'A2',
    category: 'General academic',
  },
  {
    word: 'environment',
    phonetic: '[ɪnˈvaɪrənmənt]',
    partOfSpeech: 'noun',
    definition: 'The natural world, or the conditions in which someone lives.',
    mongolian: 'байгаль орчин, орчин',
    example: 'Plastic waste is harmful to the environment.',
    level: 'A2',
    category: 'Environment',
  },
  {
    word: 'reduce',
    phonetic: '[rɪˈdjuːs]',
    partOfSpeech: 'verb',
    definition: 'To make something smaller in size, amount or number.',
    mongolian: 'багасгах, бууруулах',
    example: 'Cities are trying to reduce air pollution.',
    level: 'A2',
    category: 'Environment',
  },
  {
    word: 'opinion',
    phonetic: '[əˈpɪnjən]',
    partOfSpeech: 'noun',
    definition: 'A view or belief about something, not based on certainty.',
    mongolian: 'санал, бодол',
    example: 'In my opinion, public transport should be free.',
    level: 'A2',
    category: 'Writing & Speaking',
  },
  {
    word: 'increase',
    phonetic: '[ɪnˈkriːs]',
    partOfSpeech: 'verb',
    definition: 'To become larger in number, amount or degree.',
    mongolian: 'нэмэгдэх, өсөх',
    example: 'The number of students increased sharply after 2010.',
    level: 'A2',
    category: 'Task 1 data',
  },
  {
    word: 'decrease',
    phonetic: '[dɪˈkriːs]',
    partOfSpeech: 'verb',
    definition: 'To become smaller in number, amount or degree.',
    mongolian: 'буурах, цөөрөх',
    example: 'Sales decreased steadily over the winter months.',
    level: 'A2',
    category: 'Task 1 data',
  },
  {
    word: 'benefit',
    phonetic: '[ˈbenɪfɪt]',
    partOfSpeech: 'noun',
    definition: 'An advantage or helpful effect that something brings.',
    mongolian: 'ашиг тус, давуу тал',
    example: 'Exercise has many benefits for both body and mind.',
    level: 'A2',
    category: 'General academic',
  },
  {
    word: 'develop',
    phonetic: '[dɪˈveləp]',
    partOfSpeech: 'verb',
    definition: 'To grow or change into a more advanced form, or to create.',
    mongolian: 'хөгжүүлэх, хөгжих',
    example: 'The company developed a new way to recycle glass.',
    level: 'A2',
    category: 'General academic',
  },

  // ----- B1 · core IELTS argument & description -----------------------------
  {
    word: 'significant',
    phonetic: '[sɪɡˈnɪfɪkənt]',
    partOfSpeech: 'adjective',
    definition: 'Large or important enough to have an effect or be noticed.',
    mongolian: 'чухал, нөлөө бүхий, мэдэгдэхүйц',
    example: 'There was a significant rise in temperatures last year.',
    level: 'B1',
    category: 'Task 1 data',
  },
  {
    word: 'consequence',
    phonetic: '[ˈkɒnsɪkwəns]',
    partOfSpeech: 'noun',
    definition: 'A result or effect of an action or situation.',
    mongolian: 'үр дагавар, үр дүн',
    example: 'One consequence of urban growth is heavier traffic.',
    level: 'B1',
    category: 'Writing & Speaking',
  },
  {
    word: 'maintain',
    phonetic: '[meɪnˈteɪn]',
    partOfSpeech: 'verb',
    definition: 'To keep something in the same state or continue it.',
    mongolian: 'хадгалах, тогтоон барих, арчлах',
    example: 'It is hard to maintain a healthy diet while travelling.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'rural',
    phonetic: '[ˈrʊərəl]',
    partOfSpeech: 'adjective',
    definition: 'Relating to the countryside rather than the town.',
    mongolian: 'хөдөө орон нутгийн, хөдөөгийн',
    example: 'Many young people leave rural areas to find work.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'urban',
    phonetic: '[ˈɜːbən]',
    partOfSpeech: 'adjective',
    definition: 'Relating to a town or city.',
    mongolian: 'хот суурин газрын, хотын',
    example: 'Urban populations are expected to keep growing.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'efficient',
    phonetic: '[ɪˈfɪʃənt]',
    partOfSpeech: 'adjective',
    definition: 'Working well without wasting time, money or energy.',
    mongolian: 'үр ашигтай, бүтээмжтэй',
    example: 'Trains are a more efficient way to move large crowds.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'access',
    phonetic: '[ˈækses]',
    partOfSpeech: 'noun',
    definition: 'The right or ability to use or reach something.',
    mongolian: 'хүртээмж, нэвтрэх боломж',
    example: 'Everyone should have access to clean water.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'attitude',
    phonetic: '[ˈætɪtjuːd]',
    partOfSpeech: 'noun',
    definition: 'A way of thinking or feeling about something.',
    mongolian: 'хандлага, ханддаг байдал',
    example: 'Their attitude towards recycling has changed a lot.',
    level: 'B1',
    category: 'Society',
  },
  {
    word: 'encourage',
    phonetic: '[ɪnˈkʌrɪdʒ]',
    partOfSpeech: 'verb',
    definition: 'To give someone confidence or support to do something.',
    mongolian: 'дэмжих, урамшуулах',
    example: 'Schools should encourage students to read for pleasure.',
    level: 'B1',
    category: 'Writing & Speaking',
  },
  {
    word: 'achieve',
    phonetic: '[əˈtʃiːv]',
    partOfSpeech: 'verb',
    definition: 'To succeed in doing or getting something after effort.',
    mongolian: 'хүрэх, олж авах, биелүүлэх',
    example: 'She achieved a high band score after months of study.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'source',
    phonetic: '[sɔːs]',
    partOfSpeech: 'noun',
    definition: 'The place, person or thing that something comes from.',
    mongolian: 'эх үүсвэр, сурвалж',
    example: 'The sun is a renewable source of energy.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'method',
    phonetic: '[ˈmeθəd]',
    partOfSpeech: 'noun',
    definition: 'A particular way of doing something.',
    mongolian: 'арга, аргачлал',
    example: 'Researchers tested a new method for storing solar power.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'feature',
    phonetic: '[ˈfiːtʃə]',
    partOfSpeech: 'noun',
    definition: 'A typical or important part or quality of something.',
    mongolian: 'онцлог, шинж чанар',
    example: 'A key feature of the design is its low cost.',
    level: 'B1',
    category: 'General academic',
  },
  {
    word: 'overall',
    phonetic: '[ˌəʊvərˈɔːl]',
    partOfSpeech: 'adverb',
    definition: 'Considering everything; in general.',
    mongolian: 'нийтдээ, ерөнхийдөө',
    example: 'Overall, the graph shows an upward trend.',
    level: 'B1',
    category: 'Task 1 data',
  },
  {
    word: 'majority',
    phonetic: '[məˈdʒɒrəti]',
    partOfSpeech: 'noun',
    definition: 'The larger number or part of a group.',
    mongolian: 'олонх, дийлэнх хэсэг',
    example: 'The majority of respondents preferred online classes.',
    level: 'B1',
    category: 'Task 1 data',
  },

  // ----- B2 · upper-intermediate IELTS register -----------------------------
  {
    word: 'consume',
    phonetic: '[kənˈsjuːm]',
    partOfSpeech: 'verb',
    definition: 'To use up resources such as energy, food or fuel.',
    mongolian: 'хэрэглэх, зарцуулах',
    example: 'Older buildings tend to consume far more energy.',
    level: 'B2',
    category: 'Environment',
  },
  {
    word: 'sustainable',
    phonetic: '[səˈsteɪnəbl]',
    partOfSpeech: 'adjective',
    definition: 'Able to continue over time without harming the environment.',
    mongolian: 'тогтвортой, хүрээлэн орчинд хор хөнөөлгүй',
    example: 'Wind power is a sustainable alternative to coal.',
    level: 'B2',
    category: 'Environment',
  },
  {
    word: 'demonstrate',
    phonetic: '[ˈdemənstreɪt]',
    partOfSpeech: 'verb',
    definition: 'To show clearly that something exists or is true.',
    mongolian: 'харуулах, нотлох, илэрхийлэх',
    example: 'The study demonstrates a link between sleep and memory.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'considerable',
    phonetic: '[kənˈsɪdərəbl]',
    partOfSpeech: 'adjective',
    definition: 'Large in size, amount or degree.',
    mongolian: 'нэлээд их, мэдэгдэхүйц хэмжээний',
    example: 'A considerable amount of food is wasted each year.',
    level: 'B2',
    category: 'Task 1 data',
  },
  {
    word: 'fluctuate',
    phonetic: '[ˈflʌktʃueɪt]',
    partOfSpeech: 'verb',
    definition: 'To change frequently from high to low and back.',
    mongolian: 'хэлбэлзэх, өөрчлөгдөж байх',
    example: 'Prices fluctuated wildly during the year.',
    level: 'B2',
    category: 'Task 1 data',
  },
  {
    word: 'phenomenon',
    phonetic: '[fəˈnɒmɪnən]',
    partOfSpeech: 'noun',
    definition: 'A fact or event, especially one that is studied.',
    mongolian: 'үзэгдэл, тохиолдол',
    example: 'Global warming is a well-documented phenomenon.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'crucial',
    phonetic: '[ˈkruːʃəl]',
    partOfSpeech: 'adjective',
    definition: 'Extremely important because it affects the outcome.',
    mongolian: 'нэн чухал, шийдвэрлэх ач холбогдолтой',
    example: 'Early education is crucial for a child’s development.',
    level: 'B2',
    category: 'Writing & Speaking',
  },
  {
    word: 'tend',
    phonetic: '[tend]',
    partOfSpeech: 'verb',
    definition: 'To be likely to behave in a particular way or happen often.',
    mongolian: 'хандлагатай байх, ихэвчлэн ... байх',
    example: 'People tend to spend more during the holidays.',
    level: 'B2',
    category: 'Writing & Speaking',
  },
  {
    word: 'factor',
    phonetic: '[ˈfæktə]',
    partOfSpeech: 'noun',
    definition: 'One of the things that influences a result or situation.',
    mongolian: 'хүчин зүйл, нөлөөлөх зүйл',
    example: 'Cost is the main factor in choosing transport.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'impact',
    phonetic: '[ˈɪmpækt]',
    partOfSpeech: 'noun',
    definition: 'A powerful effect that something has on a situation.',
    mongolian: 'нөлөө, нөлөөлөл',
    example: 'Tourism has a major impact on the local economy.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'priority',
    phonetic: '[praɪˈɒrəti]',
    partOfSpeech: 'noun',
    definition: 'Something treated as more important than other things.',
    mongolian: 'тэргүүлэх чиглэл, нэн тэргүүний зүйл',
    example: 'Reducing waste should be a national priority.',
    level: 'B2',
    category: 'Writing & Speaking',
  },
  {
    word: 'allocate',
    phonetic: '[ˈæləkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To officially give a share of resources for a purpose.',
    mongolian: 'хуваарилах, зарцуулахаар хэмжих',
    example: 'The government allocated more funds to public health.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'estimate',
    phonetic: '[ˈestɪmeɪt]',
    partOfSpeech: 'verb',
    definition: 'To guess or calculate an amount roughly.',
    mongolian: 'тооцоолох, барагцаалах',
    example: 'Experts estimate that the city will double in size.',
    level: 'B2',
    category: 'Task 1 data',
  },
  {
    word: 'distinguish',
    phonetic: '[dɪˈstɪŋɡwɪʃ]',
    partOfSpeech: 'verb',
    definition: 'To recognise or show the difference between things.',
    mongolian: 'ялгах, ялгаж салгах',
    example: 'It can be hard to distinguish fact from opinion online.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'flexible',
    phonetic: '[ˈfleksəbl]',
    partOfSpeech: 'adjective',
    definition: 'Able to change or be changed easily to suit conditions.',
    mongolian: 'уян хатан, дасан зохицдог',
    example: 'Flexible working hours help parents balance their lives.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'reliable',
    phonetic: '[rɪˈlaɪəbl]',
    partOfSpeech: 'adjective',
    definition: 'That can be trusted to work well or be accurate.',
    mongolian: 'найдвартай, итгэл хүлээх',
    example: 'We need reliable data before drawing conclusions.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'contribute',
    phonetic: '[kənˈtrɪbjuːt]',
    partOfSpeech: 'verb',
    definition: 'To help cause or add to a result or situation.',
    mongolian: 'хувь нэмэр оруулах, нэмэр болох',
    example: 'Cars contribute heavily to urban pollution.',
    level: 'B2',
    category: 'Environment',
  },
  {
    word: 'rural-urban migration',
    phonetic: '[ˌrʊərəl ˈɜːbən maɪˈɡreɪʃən]',
    partOfSpeech: 'noun',
    definition: 'The movement of people from the countryside into cities.',
    mongolian: 'хөдөөгөөс хот руу шилжих хөдөлгөөн',
    example: 'Rural-urban migration has strained city housing.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'widespread',
    phonetic: '[ˈwaɪdspred]',
    partOfSpeech: 'adjective',
    definition: 'Existing or happening over a large area or among many people.',
    mongolian: 'өргөн тархсан, түгээмэл',
    example: 'Smartphones are now in widespread use everywhere.',
    level: 'B2',
    category: 'Society',
  },
  {
    word: 'emphasise',
    phonetic: '[ˈemfəsaɪz]',
    partOfSpeech: 'verb',
    definition: 'To give special importance or attention to something.',
    mongolian: 'онцлох, чухалчлах',
    example: 'The report emphasises the need for clean energy.',
    level: 'B2',
    category: 'Writing & Speaking',
  },
  {
    word: 'alternative',
    phonetic: '[ɔːlˈtɜːnətɪv]',
    partOfSpeech: 'noun',
    definition: 'A different option that can be chosen instead.',
    mongolian: 'өөр сонголт, хувилбар',
    example: 'Cycling is a healthy alternative to driving.',
    level: 'B2',
    category: 'General academic',
  },
  {
    word: 'expenditure',
    phonetic: '[ɪkˈspendɪtʃə]',
    partOfSpeech: 'noun',
    definition: 'The amount of money that is spent.',
    mongolian: 'зарлага, зарцуулалт',
    example: 'Household expenditure on food rose last year.',
    level: 'B2',
    category: 'Task 1 data',
  },
  {
    word: 'proportion',
    phonetic: '[prəˈpɔːʃən]',
    partOfSpeech: 'noun',
    definition: 'A part or share of a whole, often as a percentage.',
    mongolian: 'хувь хэмжээ, эзлэх хувь',
    example: 'A large proportion of the budget went to transport.',
    level: 'B2',
    category: 'Task 1 data',
  },
  {
    word: 'distribution',
    phonetic: '[ˌdɪstrɪˈbjuːʃən]',
    partOfSpeech: 'noun',
    definition: 'The way something is shared out or spread over an area.',
    mongolian: 'хуваарилалт, тархалт',
    example: 'The map shows the distribution of rainfall across the country.',
    level: 'B2',
    category: 'Task 1 data',
  },

  // ----- C1 · advanced academic IELTS ---------------------------------------
  {
    word: 'mitigate',
    phonetic: '[ˈmɪtɪɡeɪt]',
    partOfSpeech: 'verb',
    definition: 'To make something bad less severe or harmful.',
    mongolian: 'зөөлрүүлэх, бууруулах, хохирлыг багасгах',
    example: 'Planting trees can help mitigate the effects of pollution.',
    level: 'C1',
    category: 'Environment',
  },
  {
    word: 'detrimental',
    phonetic: '[ˌdetrɪˈmentl]',
    partOfSpeech: 'adjective',
    definition: 'Causing harm or damage.',
    mongolian: 'хор хөнөөлтэй, сөрөг нөлөөтэй',
    example: 'A lack of sleep is detrimental to concentration.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'comprehensive',
    phonetic: '[ˌkɒmprɪˈhensɪv]',
    partOfSpeech: 'adjective',
    definition: 'Complete and including all or nearly all elements.',
    mongolian: 'иж бүрэн, бүрэн гүйцэт',
    example: 'The book gives a comprehensive overview of the topic.',
    level: 'C1',
    category: 'General academic',
  },
  {
    word: 'subsequently',
    phonetic: '[ˈsʌbsɪkwəntli]',
    partOfSpeech: 'adverb',
    definition: 'Afterwards; following something in time or order.',
    mongolian: 'дараа нь, улмаар',
    example: 'The policy was introduced and subsequently revised.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'predominantly',
    phonetic: '[prɪˈdɒmɪnəntli]',
    partOfSpeech: 'adverb',
    definition: 'Mainly; for the most part.',
    mongolian: 'голчлон, ихэвчлэн',
    example: 'The workforce is predominantly young and educated.',
    level: 'C1',
    category: 'General academic',
  },
  {
    word: 'undermine',
    phonetic: '[ˌʌndəˈmaɪn]',
    partOfSpeech: 'verb',
    definition: 'To gradually weaken something or make it less effective.',
    mongolian: 'сулруулах, доройтуулах',
    example: 'Misinformation can undermine public trust in science.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'inevitable',
    phonetic: '[ɪnˈevɪtəbl]',
    partOfSpeech: 'adjective',
    definition: 'Certain to happen and impossible to avoid.',
    mongolian: 'зайлшгүй, гарцаагүй болох',
    example: 'Some change is inevitable as technology advances.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'profound',
    phonetic: '[prəˈfaʊnd]',
    partOfSpeech: 'adjective',
    definition: 'Very great, deep or intense in effect.',
    mongolian: 'гүн гүнзгий, асар их нөлөөтэй',
    example: 'The internet has had a profound effect on society.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'correlation',
    phonetic: '[ˌkɒrəˈleɪʃən]',
    partOfSpeech: 'noun',
    definition: 'A connection between two things that change together.',
    mongolian: 'хамаарал, харилцан хамаарал',
    example: 'There is a strong correlation between income and health.',
    level: 'C1',
    category: 'General academic',
  },
  {
    word: 'implement',
    phonetic: '[ˈɪmplɪment]',
    partOfSpeech: 'verb',
    definition: 'To put a plan, decision or system into action.',
    mongolian: 'хэрэгжүүлэх, биелүүлэх',
    example: 'The council implemented a new recycling scheme.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'fundamental',
    phonetic: '[ˌfʌndəˈmentl]',
    partOfSpeech: 'adjective',
    definition: 'Forming a necessary base or core; of central importance.',
    mongolian: 'үндсэн, суурь, гол',
    example: 'Access to education is a fundamental human right.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'incentive',
    phonetic: '[ɪnˈsentɪv]',
    partOfSpeech: 'noun',
    definition: 'Something that encourages a person to do something.',
    mongolian: 'урамшуулал, өдөөгч хүчин зүйл',
    example: 'Tax breaks act as an incentive to buy electric cars.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'compelling',
    phonetic: '[kəmˈpelɪŋ]',
    partOfSpeech: 'adjective',
    definition: 'So strong or convincing that it demands attention.',
    mongolian: 'итгүүлэм, нөлөөтэй, татах хүчтэй',
    example: 'The author presents a compelling argument for reform.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'discrepancy',
    phonetic: '[dɪsˈkrepənsi]',
    partOfSpeech: 'noun',
    definition: 'A difference between two things that should match.',
    mongolian: 'зөрүү, үл нийцэл',
    example: 'There was a discrepancy between the two sets of figures.',
    level: 'C1',
    category: 'Task 1 data',
  },
  {
    word: 'cumulative',
    phonetic: '[ˈkjuːmjələtɪv]',
    partOfSpeech: 'adjective',
    definition: 'Increasing gradually as more is added.',
    mongolian: 'хуримтлагдсан, нэмэгдсээр байгаа',
    example: 'The cumulative effect of small savings is large.',
    level: 'C1',
    category: 'Task 1 data',
  },
  {
    word: 'prevalent',
    phonetic: '[ˈprevələnt]',
    partOfSpeech: 'adjective',
    definition: 'Common or widespread in a particular place or time.',
    mongolian: 'түгээмэл, өргөн тархсан',
    example: 'This attitude is especially prevalent among teenagers.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'advocate',
    phonetic: '[ˈædvəkeɪt]',
    partOfSpeech: 'verb',
    definition: 'To publicly support or recommend a particular cause.',
    mongolian: 'дэмжих, талд нь зогсох, уриалах',
    example: 'Many scientists advocate cutting carbon emissions.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'diverse',
    phonetic: '[daɪˈvɜːs]',
    partOfSpeech: 'adjective',
    definition: 'Including many different types of people or things.',
    mongolian: 'олон янзын, олон талт',
    example: 'The city has a diverse and multilingual population.',
    level: 'C1',
    category: 'Society',
  },
  {
    word: 'notwithstanding',
    phonetic: '[ˌnɒtwɪθˈstændɪŋ]',
    partOfSpeech: 'preposition',
    definition: 'In spite of; without being affected by something.',
    mongolian: 'үл харгалзан, хэдийгээр ... ч',
    example: 'Notwithstanding the costs, the benefits are clear.',
    level: 'C1',
    category: 'Writing & Speaking',
  },
  {
    word: 'plateau',
    phonetic: '[ˈplætəʊ]',
    partOfSpeech: 'verb',
    definition: 'To stay at a steady level after a period of change.',
    mongolian: 'тогтворжих, нэг түвшинд тогтох',
    example: 'Sales rose quickly and then plateaued in June.',
    level: 'C1',
    category: 'Task 1 data',
  },
  {
    word: 'negligible',
    phonetic: '[ˈneɡlɪdʒəbl]',
    partOfSpeech: 'adjective',
    definition: 'So small or unimportant as to be not worth considering.',
    mongolian: 'үл ялиг, тоомжиргүй бага',
    example: 'The difference between the two methods was negligible.',
    level: 'C1',
    category: 'Task 1 data',
  },
  {
    word: 'scrutiny',
    phonetic: '[ˈskruːtəni]',
    partOfSpeech: 'noun',
    definition: 'Careful and detailed examination of something.',
    mongolian: 'нарийн шалгалт, нягт нямбай судлал',
    example: 'The plan came under close public scrutiny.',
    level: 'C1',
    category: 'General academic',
  },

  // ----- C2 · sophisticated / band 8+ ---------------------------------------
  {
    word: 'ubiquitous',
    phonetic: '[juːˈbɪkwɪtəs]',
    partOfSpeech: 'adjective',
    definition: 'Present, appearing or found everywhere.',
    mongolian: 'хаа сайгүй байдаг, түгээмэл тархсан',
    example: 'Mobile phones have become ubiquitous in modern life.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'exacerbate',
    phonetic: '[ɪɡˈzæsəbeɪt]',
    partOfSpeech: 'verb',
    definition: 'To make a bad situation, problem or feeling worse.',
    mongolian: 'улам хүндрүүлэх, дордуулах',
    example: 'Cutting trees only exacerbates soil erosion.',
    level: 'C2',
    category: 'Environment',
  },
  {
    word: 'paradigm',
    phonetic: '[ˈpærədaɪm]',
    partOfSpeech: 'noun',
    definition: 'A typical example or model of how something works.',
    mongolian: 'жишиг загвар, парадигм',
    example: 'Remote work has created a new paradigm for offices.',
    level: 'C2',
    category: 'General academic',
  },
  {
    word: 'paramount',
    phonetic: '[ˈpærəmaʊnt]',
    partOfSpeech: 'adjective',
    definition: 'More important than anything else; supreme.',
    mongolian: 'хамгийн чухал, дээд зэргийн ач холбогдолтой',
    example: 'Safety is of paramount importance on construction sites.',
    level: 'C2',
    category: 'Writing & Speaking',
  },
  {
    word: 'nuanced',
    phonetic: '[ˈnjuːɑːnst]',
    partOfSpeech: 'adjective',
    definition: 'Showing subtle differences in meaning or expression.',
    mongolian: 'нарийн ялгаатай, нюанстай',
    example: 'The debate calls for a more nuanced view of the issue.',
    level: 'C2',
    category: 'Writing & Speaking',
  },
  {
    word: 'pervasive',
    phonetic: '[pəˈveɪsɪv]',
    partOfSpeech: 'adjective',
    definition: 'Spreading widely and present in every part of something.',
    mongolian: 'нэвчсэн, хаа сайгүй нэвтэрсэн',
    example: 'Advertising has a pervasive influence on young people.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'unprecedented',
    phonetic: '[ʌnˈpresɪdentɪd]',
    partOfSpeech: 'adjective',
    definition: 'Never having happened or existed before.',
    mongolian: 'урьд өмнө байгаагүй, бүрэн шинэ',
    example: 'The pandemic caused unprecedented disruption to travel.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'culminate',
    phonetic: '[ˈkʌlmɪneɪt]',
    partOfSpeech: 'verb',
    definition: 'To reach a final or highest point, especially as a result.',
    mongolian: 'оргилдоо хүрэх, эцэст нь хүрэх',
    example: 'Years of research culminated in a major breakthrough.',
    level: 'C2',
    category: 'General academic',
  },
  {
    word: 'tangible',
    phonetic: '[ˈtændʒəbl]',
    partOfSpeech: 'adjective',
    definition: 'Real and definite enough to be clearly seen or felt.',
    mongolian: 'бодит, гар дамжих, тодорхой мэдрэгдэхүйц',
    example: 'The project produced tangible improvements in air quality.',
    level: 'C2',
    category: 'Writing & Speaking',
  },
  {
    word: 'disparity',
    phonetic: '[dɪˈspærəti]',
    partOfSpeech: 'noun',
    definition: 'A great difference, especially an unfair one.',
    mongolian: 'тэгш бус байдал, ялгаа зөрүү',
    example: 'There is a wide disparity in income between regions.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'resilient',
    phonetic: '[rɪˈzɪliənt]',
    partOfSpeech: 'adjective',
    definition: 'Able to recover quickly from difficulty or change.',
    mongolian: 'тэсвэртэй, хурдан сэргэдэг',
    example: 'Local businesses proved remarkably resilient in the crisis.',
    level: 'C2',
    category: 'Society',
  },
  {
    word: 'inherent',
    phonetic: '[ɪnˈhɪərənt]',
    partOfSpeech: 'adjective',
    definition: 'Existing as a natural and permanent part of something.',
    mongolian: 'төрөлхийн, угаасаа байдаг, салшгүй',
    example: 'There are inherent risks in any new technology.',
    level: 'C2',
    category: 'General academic',
  },
  {
    word: 'constitute',
    phonetic: '[ˈkɒnstɪtjuːt]',
    partOfSpeech: 'verb',
    definition: 'To be or be considered as the parts that form a whole.',
    mongolian: 'бүрдүүлэх, болох, тооцогдох',
    example: 'Women constitute over half of the student body.',
    level: 'C2',
    category: 'Task 1 data',
  },
  {
    word: 'cohesion',
    phonetic: '[kəʊˈhiːʒən]',
    partOfSpeech: 'noun',
    definition: 'The way the parts of a text or group hold together as a whole.',
    mongolian: 'уялдаа холбоо, нэгдмэл байдал',
    example: 'Linking words give an essay cohesion and flow.',
    level: 'C2',
    category: 'Writing & Speaking',
  },
  {
    word: 'aggregate',
    phonetic: '[ˈæɡrɪɡət]',
    partOfSpeech: 'noun',
    definition: 'A total formed by combining several separate amounts.',
    mongolian: 'нийлбэр, нэгтгэсэн дүн',
    example: 'In aggregate, the three sectors employ most workers.',
    level: 'C2',
    category: 'Task 1 data',
  },
  {
    word: 'salient',
    phonetic: '[ˈseɪliənt]',
    partOfSpeech: 'adjective',
    definition: 'Most noticeable or important; standing out.',
    mongolian: 'тод томруун, гол анхаарал татах',
    example: 'The report highlights the salient features of the trend.',
    level: 'C2',
    category: 'Task 1 data',
  },
];

// Curated deck above + the machine-generated, deduped NotebookLM bank.
// Consumers import IELTS_VOCAB unchanged (now the full merged set).
export const IELTS_VOCAB: ExamVocab[] = [...IELTS_VOCAB_CURATED, ...IELTS_VOCAB_GENERATED];
