// AUTO-GENERATED by scripts/generateVocabulary.ts — do not edit by hand.
// German seed words (article/class/level) authored in scripts/seedWords.ts;
// Mongolian meanings + example sentences generated via the Gemini API.
// Regenerate with:  npx tsx scripts/generateVocabulary.ts
import { VocabularyWord } from './types';

export const GENERATED_VOCABULARY: VocabularyWord[] = [
  {
    "german": "Apfel",
    "article": "der",
    "mongolian": "алим",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ich esse jeden Tag einen Apfel.",
    "exampleMongolian": "Би өдөр бүр нэг алим иддэг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Banane",
    "article": "die",
    "mongolian": "банан / гадил",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Die Banane ist süß und lecker.",
    "exampleMongolian": "Банан нь чихэрлэг бөгөөд амттай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Brot",
    "article": "das",
    "mongolian": "талх",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich kaufe frisches Brot beim Bäcker.",
    "exampleMongolian": "Би талхны газраас шинэ талх худалдаж авдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Butter",
    "article": "die",
    "mongolian": "цөцгийн тос",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Bitte schmier mir Butter aufs Brot.",
    "exampleMongolian": "Талхан дээр минь цөцгийн тос түрхээд өгөөч.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Käse",
    "article": "der",
    "mongolian": "бяслаг",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Magst du Käse auf der Pizza?",
    "exampleMongolian": "Чи пиццан дээрх бяслагт дуртай юу?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Ei",
    "article": "das",
    "mongolian": "өндөг",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich möchte ein weichgekochtes Ei zum Frühstück.",
    "exampleMongolian": "Би өглөөний цайндаа зөөлөн чанасан өндөг идмээр байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Fisch",
    "article": "der",
    "mongolian": "загас",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Am Freitag essen wir oft Fisch.",
    "exampleMongolian": "Баасан гарагт бид ихэвчлэн загас иддэг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Fleisch",
    "article": "das",
    "mongolian": "мах",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Vegetarier essen kein Fleisch.",
    "exampleMongolian": "Цагаан хоолтон хүмүүс мах иддэггүй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Milch",
    "article": "die",
    "mongolian": "сүү",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Trinkst du deinen Kaffee mit Milch?",
    "exampleMongolian": "Чи кофегоо сүүтэй уудаг уу?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Kaffee",
    "article": "der",
    "mongolian": "кофе",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Morgens brauche ich immer eine Tasse Kaffee.",
    "exampleMongolian": "Өглөө надад заавал нэг аяга кофе хэрэгтэй байдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Tee",
    "article": "der",
    "mongolian": "цай",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Im Winter trinke ich gerne heißen Tee.",
    "exampleMongolian": "Өвөл би халуун цай уух дуртай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Saft",
    "article": "der",
    "mongolian": "шүүс",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Möchtest du ein Glas Orangensaft?",
    "exampleMongolian": "Чи нэг аяга жүржийн шүүс уумаар байна уу?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Bier",
    "article": "das",
    "mongolian": "шар айраг / пиво",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich trinke am Wochenende ein Bier.",
    "exampleMongolian": "Би амралтын өдрөөр шар айраг уудаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Wein",
    "article": "der",
    "mongolian": "дарс",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Möchten Sie Rotwein oder Weißwein?",
    "exampleMongolian": "Та улаан дарс уух уу, эсвэл цагаан дарс уух уу?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Zucker",
    "article": "der",
    "mongolian": "элсэн чихэр / чихэр",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Trinken Sie Kaffee mit oder ohne Zucker?",
    "exampleMongolian": "Та кофег элсэн чихэртэй эсвэл чихэргүй уудаг уу?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Salz",
    "article": "das",
    "mongolian": "давс",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Bitte geben Sie mir das Salz.",
    "exampleMongolian": "Надад давс өгөөч.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Suppe",
    "article": "die",
    "mongolian": "шөл",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Die Suppe schmeckt sehr lecker.",
    "exampleMongolian": "Энэ шөл маш амттай байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Kartoffel",
    "article": "die",
    "mongolian": "төмс",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Ich kaufe ein Kilo Kartoffeln.",
    "exampleMongolian": "Би нэг килограмм төмс худалдаж авна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Gemüse",
    "article": "das",
    "mongolian": "хүнсний ногоо / ногоо",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Wir essen jeden Tag frisches Gemüse.",
    "exampleMongolian": "Бид өдөр бүр шинэ хүнсний ногоо иддэг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Obst",
    "article": "das",
    "mongolian": "жимс",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Kinder sollten viel Obst essen.",
    "exampleMongolian": "Хүүхдүүд их жимс идэх хэрэгтэй.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Kuchen",
    "article": "der",
    "mongolian": "бялуу",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Meine Mutter backt heute einen Kuchen.",
    "exampleMongolian": "Ээж маань өнөөдөр бялуу жигнэж байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Vater",
    "article": "der",
    "mongolian": "аав / эцэг",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Mein Vater arbeitet als Arzt.",
    "exampleMongolian": "Миний аав эмчээр ажилладаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Mutter",
    "article": "die",
    "mongolian": "ээж / эх",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Meine Mutter kocht sehr gut.",
    "exampleMongolian": "Миний ээж маш сайн хоол хийдэг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Bruder",
    "article": "der",
    "mongolian": "ах / эрэгтэй дүү",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ich habe einen älteren Bruder.",
    "exampleMongolian": "Би нэг ахтай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Schwester",
    "article": "die",
    "mongolian": "эгч / эмэгтэй дүү",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Meine Schwester wohnt in Berlin.",
    "exampleMongolian": "Миний эгч Берлинд амьдардаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Eltern",
    "article": "die",
    "mongolian": "эцэг эх",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Meine Eltern leben auf dem Land.",
    "exampleMongolian": "Миний эцэг эх хөдөө амьдардаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Sohn",
    "article": "der",
    "mongolian": "хүү",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ihr Sohn geht schon in die Schule.",
    "exampleMongolian": "Түүний хүү хэдийн сургуульд явдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Tochter",
    "article": "die",
    "mongolian": "охин",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Wie alt ist Ihre Tochter?",
    "exampleMongolian": "Таны охин хэдэн настай вэ?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Junge",
    "article": "der",
    "mongolian": "хүү / эрэгтэй хүүхэд",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Der Junge spielt im Garten mit dem Ball.",
    "exampleMongolian": "Хүү цэцэрлэгт бөмбөгөөр тоглож байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Mädchen",
    "article": "das",
    "mongolian": "охин / эмэгтэй хүүхэд",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Das Mädchen liest ein spannendes Buch.",
    "exampleMongolian": "Охин сонирхолтой ном уншиж байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Mensch",
    "article": "der",
    "mongolian": "хүн",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Jeder Mensch braucht Freunde.",
    "exampleMongolian": "Хүн бүрт найз нөхөд хэрэгтэй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Lehrer",
    "article": "der",
    "mongolian": "багш / эрэгтэй багш",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Unser Lehrer ist sehr nett.",
    "exampleMongolian": "Манай багш маш эелдэг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Schüler",
    "article": "der",
    "mongolian": "сурагч",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Die Schüler haben heute keine Hausaufgaben.",
    "exampleMongolian": "Сурагчид өнөөдөр гэрийн даалгаваргүй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Student",
    "article": "der",
    "mongolian": "оюутан",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Er ist Student an der Universität München.",
    "exampleMongolian": "Тэр Мюнхений их сургуулийн оюутан.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Arzt",
    "article": "der",
    "mongolian": "эмч",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Ich muss morgen zum Arzt gehen.",
    "exampleMongolian": "Би маргааш эмчид үзүүлэх ёстой.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Beruf",
    "article": "der",
    "mongolian": "мэргэжил / ажил",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Was bist du von Beruf?",
    "exampleMongolian": "Та ямар мэргэжилтэй вэ?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Nachbar",
    "article": "der",
    "mongolian": "хөрш / хөрш айл",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Mein Nachbar ist sehr freundlich.",
    "exampleMongolian": "Миний хөрш маш найрсаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Gast",
    "article": "der",
    "mongolian": "зочин / гийчин",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Heute Abend haben wir einen Gast zum Abendessen.",
    "exampleMongolian": "Өнөө орой бид оройн хоолонд зочинтой.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Chef",
    "article": "der",
    "mongolian": "дарга / удирдагч",
    "category": "Нэр үг (Эрэгтэй - B1)",
    "exampleGerman": "Ich muss meinen Chef nach Urlaub fragen.",
    "exampleMongolian": "Би даргаасаа амралт асуух хэрэгтэй байна.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Kollege",
    "article": "der",
    "mongolian": "хамт ажиллагч / хамтран ажиллагч",
    "category": "Нэр үг (Эрэгтэй - B1)",
    "exampleGerman": "Mein Kollege hilft mir bei der Arbeit.",
    "exampleMongolian": "Миний хамтран ажиллагч надад ажилд тусалдаг.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Auto",
    "article": "das",
    "mongolian": "машин / автомашин",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Mein Auto ist blau.",
    "exampleMongolian": "Миний машин цэнхэр өнгөтэй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Bus",
    "article": "der",
    "mongolian": "автобус",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ich fahre mit dem Bus zur Schule.",
    "exampleMongolian": "Би автобусаар сургууль руугаа явдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Zug",
    "article": "der",
    "mongolian": "галт тэрэг",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Der Zug kommt um 10 Uhr an.",
    "exampleMongolian": "Галт тэрэг 10 цагт ирнэ.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Fahrrad",
    "article": "das",
    "mongolian": "унадаг дугуй / дугуй",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Fährst du gerne Fahrrad?",
    "exampleMongolian": "Та унадаг дугуй унах дуртай юу?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Straße",
    "article": "die",
    "mongolian": "гудамж / зам",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Diese Straße ist sehr lang.",
    "exampleMongolian": "Энэ гудамж маш урт юм.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Weg",
    "article": "der",
    "mongolian": "зам / жим",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Kennst du den Weg zum Bahnhof?",
    "exampleMongolian": "Та вокзал орох замыг мэдэх үү?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Dorf",
    "article": "das",
    "mongolian": "тосгон / суурин",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Meine Großeltern leben in einem kleinen Dorf.",
    "exampleMongolian": "Миний өвөө эмээ хоёр нэгэн жижиг тосгонд амьдардаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Wohnung",
    "article": "die",
    "mongolian": "байр / орон сууц",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Unsere Wohnung hat drei Zimmer.",
    "exampleMongolian": "Манай байр гурван өрөөтэй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Zimmer",
    "article": "das",
    "mongolian": "өрөө",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Mein Zimmer ist groß und hell.",
    "exampleMongolian": "Миний өрөө том бөгөөд саруулхан.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Küche",
    "article": "die",
    "mongolian": "гал тогоо / гал тогооны өрөө",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Sie kocht in der Küche das Abendessen.",
    "exampleMongolian": "Тэр гал тогоонд оройн хоол хийж байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Bett",
    "article": "das",
    "mongolian": "ор",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Das Bett im Hotel war sehr bequem.",
    "exampleMongolian": "Буудлын ор маш тухтай байсан.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Stuhl",
    "article": "der",
    "mongolian": "сандал",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Bitte nimm dir einen Stuhl.",
    "exampleMongolian": "Чи нэг сандал аваарай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Lampe",
    "article": "die",
    "mongolian": "чийдэн / гэрэл",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Ich brauche eine neue Lampe für meinen Schreibtisch.",
    "exampleMongolian": "Би бичгийн ширээндээ шинэ чийдэн авах хэрэгтэй байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Fenster",
    "article": "das",
    "mongolian": "цонх",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Kannst du bitte das Fenster aufmachen?",
    "exampleMongolian": "Цонхоо нээж өгөхгүй юү?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Schrank",
    "article": "der",
    "mongolian": "шүүгээ / хувцасны шүүгээ",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Häng deine Jacke bitte in den Schrank.",
    "exampleMongolian": "Хүрмээ шүүгээнд хийгээрэй.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Uhr",
    "article": "die",
    "mongolian": "цаг / бугуйн цаг",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Meine Uhr ist kaputt.",
    "exampleMongolian": "Миний цаг эвдэрчихсэн.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Telefon",
    "article": "das",
    "mongolian": "утас / суурин утас",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Das Telefon klingelt schon wieder.",
    "exampleMongolian": "Утас дахиад л дуугараад байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Handy",
    "article": "das",
    "mongolian": "гар утас",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich habe mein Handy zu Hause vergessen.",
    "exampleMongolian": "Би гар утсаа гэртээ мартчихаж.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Computer",
    "article": "der",
    "mongolian": "компьютер",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ich arbeite jeden Tag am Computer.",
    "exampleMongolian": "Би өдөр бүр компьютер дээр ажилладаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Bank",
    "article": "die",
    "mongolian": "банк / сандал",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Ich muss heute noch zur Bank gehen, um Geld abzuheben.",
    "exampleMongolian": "Би өнөөдөр мөнгө авахаар банк руу явах хэрэгтэй.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Supermarkt",
    "article": "der",
    "mongolian": "супермаркет / сүлжээ дэлгүүр",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ich kaufe Milch im Supermarkt.",
    "exampleMongolian": "Би супермаркетаас сүү худалдаж авдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Markt",
    "article": "der",
    "mongolian": "зах / худалдааны төв",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Am Samstag gehe ich auf den Markt.",
    "exampleMongolian": "Хагас сайн өдөр би зах ордог.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Geschäft",
    "article": "das",
    "mongolian": "дэлгүүр / албан газар",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Dieses Geschäft verkauft Kleidung.",
    "exampleMongolian": "Энэ дэлгүүр хувцас зардаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Restaurant",
    "article": "das",
    "mongolian": "ресторан / гуанз",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Wir essen heute im Restaurant.",
    "exampleMongolian": "Бид өнөөдөр ресторанд хоол иднэ.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Hotel",
    "article": "das",
    "mongolian": "зочид буудал",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Das Hotel liegt im Zentrum der Stadt.",
    "exampleMongolian": "Зочид буудал хотын төвд байрладаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Universität",
    "article": "die",
    "mongolian": "их сургууль",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Sie studiert an einer Universität.",
    "exampleMongolian": "Тэр их сургуульд сурдаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Büro",
    "article": "das",
    "mongolian": "оффис / албан тасалгаа",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Mein Büro befindet sich im dritten Stock.",
    "exampleMongolian": "Миний оффис гурван давхарт байдаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Garten",
    "article": "der",
    "mongolian": "цэцэрлэг",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Die Kinder spielen im Garten.",
    "exampleMongolian": "Хүүхдүүд цэцэрлэгт тоглож байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Baum",
    "article": "der",
    "mongolian": "мод",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Vor dem Haus steht ein großer Baum.",
    "exampleMongolian": "Байшингийн өмнө нэг том мод байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Blume",
    "article": "die",
    "mongolian": "цэцэг",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Ich schenke meiner Mutter eine Blume.",
    "exampleMongolian": "Би ээждээ цэцэг бэлэглэнэ.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Hund",
    "article": "der",
    "mongolian": "нохой",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Mein Hund läuft im Park.",
    "exampleMongolian": "Миний нохой паркт гүйж байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Katze",
    "article": "die",
    "mongolian": "муур",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Die Katze schläft auf dem Sofa.",
    "exampleMongolian": "Муур буйдан дээр унтаж байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Vogel",
    "article": "der",
    "mongolian": "шувуу",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Der Vogel singt auf dem Baum.",
    "exampleMongolian": "Шувуу модон дээр дуулж байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Tier",
    "article": "das",
    "mongolian": "амьтан",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich mag Tiere, besonders Hunde.",
    "exampleMongolian": "Би амьтдад, ялангуяа нохойнд дуртай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Sonne",
    "article": "die",
    "mongolian": "нар",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Heute scheint die Sonne den ganzen Tag.",
    "exampleMongolian": "Өнөөдөр өдөржин нар гарч байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Mond",
    "article": "der",
    "mongolian": "сар",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Der Mond ist heute Nacht sehr hell.",
    "exampleMongolian": "Өнөөдөр шөнө сар маш тод байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Himmel",
    "article": "der",
    "mongolian": "тэнгэр",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Der Himmel ist heute ganz blau.",
    "exampleMongolian": "Өнөөдөр тэнгэр үнэхээр хөх байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Wetter",
    "article": "das",
    "mongolian": "цаг агаар",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Wie ist das Wetter heute in Berlin?",
    "exampleMongolian": "Өнөөдөр Берлинд цаг агаар ямар байна вэ?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Regen",
    "article": "der",
    "mongolian": "бороо",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Ich mag den Regen nicht.",
    "exampleMongolian": "Би бороонд дургүй.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Schnee",
    "article": "der",
    "mongolian": "цас",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Im Winter liegt hier viel Schnee.",
    "exampleMongolian": "Өвөл энд их цастай байдаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Sommer",
    "article": "der",
    "mongolian": "зун",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Im Sommer fahren wir ans Meer.",
    "exampleMongolian": "Зун бид далай руу явдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Winter",
    "article": "der",
    "mongolian": "өвөл",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Der Winter in der Mongolei ist sehr kalt.",
    "exampleMongolian": "Монголын өвөл маш хүйтэн байдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Abend",
    "article": "der",
    "mongolian": "орой / үдэш",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Was machst du heute Abend?",
    "exampleMongolian": "Чи өнөөдөр орой юу хийх вэ?",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Woche",
    "article": "die",
    "mongolian": "долоо хоног",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Eine Woche hat sieben Tage.",
    "exampleMongolian": "Нэг долоо хоногт долоон өдөр байдаг.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Monat",
    "article": "der",
    "mongolian": "сар",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Ein Jahr hat zwölf Monate.",
    "exampleMongolian": "Нэг жил арван хоёр сартай.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Stunde",
    "article": "die",
    "mongolian": "цаг",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Der Kurs dauert eine Stunde.",
    "exampleMongolian": "Курс нэг цаг үргэлжилнэ.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Minute",
    "article": "die",
    "mongolian": "минут",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Warten Sie bitte eine Minute.",
    "exampleMongolian": "Нэг минут хүлээнэ үү.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Sprache",
    "article": "die",
    "mongolian": "хэл",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Welche Sprachen sprechen Sie?",
    "exampleMongolian": "Та ямар хэлээр ярьдаг вэ?",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Wort",
    "article": "das",
    "mongolian": "үг",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Ich kenne dieses Wort nicht.",
    "exampleMongolian": "Би энэ үгийг мэдэхгүй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Frage",
    "article": "die",
    "mongolian": "асуулт",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Ich habe eine Frage.",
    "exampleMongolian": "Надад нэг асуулт байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Antwort",
    "article": "die",
    "mongolian": "хариулт",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Die Antwort ist richtig.",
    "exampleMongolian": "Хариулт нь зөв байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Hand",
    "article": "die",
    "mongolian": "гар",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Gib mir deine Hand.",
    "exampleMongolian": "Надад гараа өгөөч.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Kopf",
    "article": "der",
    "mongolian": "толгой",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Mein Kopf tut weh.",
    "exampleMongolian": "Миний толгой өвдөж байна.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Auge",
    "article": "das",
    "mongolian": "нүд",
    "category": "Нэр үг (Дунд - A1)",
    "exampleGerman": "Sie hat blaue Augen.",
    "exampleMongolian": "Тэр цэнхэр нүдтэй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Fuß",
    "article": "der",
    "mongolian": "хөл",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Wir gehen zu Fuß.",
    "exampleMongolian": "Бид явган явна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Herz",
    "article": "das",
    "mongolian": "зүрх",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Mein Herz schlägt schnell.",
    "exampleMongolian": "Миний зүрх хурдан цохилж байна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Kleidung",
    "article": "die",
    "mongolian": "хувцас / хувцас хунар",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Im Winter brauchen wir warme Kleidung.",
    "exampleMongolian": "Өвөл бидэнд дулаан хувцас хэрэгтэй.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Schuh",
    "article": "der",
    "mongolian": "гутал",
    "category": "Нэр үг (Эрэгтэй - A1)",
    "exampleGerman": "Deine neuen Schuhe sind sehr schön.",
    "exampleMongolian": "Чиний шинэ гутал маш гоё юм.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Jacke",
    "article": "die",
    "mongolian": "хүрэм / куртка",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Zieh bitte deine Jacke an, es ist kalt.",
    "exampleMongolian": "Хүйтэн байна, хүрэмээ өмсөөрэй.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Farbe",
    "article": "die",
    "mongolian": "өнгө / будаг",
    "category": "Нэр үг (Эмэгтэй - A1)",
    "exampleGerman": "Blau ist meine Lieblingsfarbe.",
    "exampleMongolian": "Цэнхэр бол миний дуртай өнгө.",
    "wordClass": "noun",
    "level": "A1"
  },
  {
    "german": "Reise",
    "article": "die",
    "mongolian": "аялал",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Gute Reise und viel Spaß!",
    "exampleMongolian": "Сайн яваад ирээрэй, зугаатай байгаарай!",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Urlaub",
    "article": "der",
    "mongolian": "амралт / чөлөө",
    "category": "Нэр үг (Эрэгтэй - A2)",
    "exampleGerman": "Im Sommer mache ich drei Wochen Urlaub.",
    "exampleMongolian": "Зун би гурван долоо хоног амарна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Welt",
    "article": "die",
    "mongolian": "дэлхий / ертөнц",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Es gibt viele schöne Orte auf der Welt.",
    "exampleMongolian": "Дэлхий дээр олон сайхан газар байдаг.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Problem",
    "article": "das",
    "mongolian": "асуудал / бэрхшээл",
    "category": "Нэр үг (Дунд - A2)",
    "exampleGerman": "Kein Problem, ich kann dir helfen.",
    "exampleMongolian": "Асуудалгүй ээ, би чамд тусалж чадна.",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Idee",
    "article": "die",
    "mongolian": "санаа / бодол",
    "category": "Нэр үг (Эмэгтэй - A2)",
    "exampleGerman": "Das ist eine sehr gute Idee!",
    "exampleMongolian": "Энэ маш сайн санаа байна!",
    "wordClass": "noun",
    "level": "A2"
  },
  {
    "german": "Gesundheit",
    "article": "die",
    "mongolian": "эрүүл мэнд",
    "category": "Нэр үг (Эмэгтэй - B1)",
    "exampleGerman": "Gesundheit ist das Wichtigste im Leben.",
    "exampleMongolian": "Эрүүл мэнд бол амьдралын хамгийн чухал зүйл.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Umwelt",
    "article": "die",
    "mongolian": "хүрээлэн буй орчин / байгаль орчин",
    "category": "Нэр үг (Эмэгтэй - B1)",
    "exampleGerman": "Wir müssen die Umwelt schützen.",
    "exampleMongolian": "Бид байгаль орчноо хамгаалах ёстой.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Erfahrung",
    "article": "die",
    "mongolian": "туршлага",
    "category": "Нэр үг (Эмэгтэй - B1)",
    "exampleGerman": "Er hat schon viel Erfahrung in diesem Beruf.",
    "exampleMongolian": "Тэр энэ мэргэжлээр арвин их туршлагатай.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Meinung",
    "article": "die",
    "mongolian": "бодол / санал / үзэл бодол",
    "category": "Нэр үг (Эмэгтэй - B1)",
    "exampleGerman": "Meiner Meinung nach ist das eine gute Idee.",
    "exampleMongolian": "Миний бодлоор энэ бол сайн санаа байна.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Termin",
    "article": "der",
    "mongolian": "товлосон цаг / уулзалт",
    "category": "Нэр үг (Эрэгтэй - B1)",
    "exampleGerman": "Ich habe morgen einen Termin beim Arzt.",
    "exampleMongolian": "Би маргааш эмчийн цагтай.",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "Rechnung",
    "article": "die",
    "mongolian": "тооцооны хуудас / нэхэмжлэх",
    "category": "Нэр үг (Эмэгтэй - B1)",
    "exampleGerman": "Könnte ich bitte die Rechnung haben?",
    "exampleMongolian": "Би тооцооны хуудсаа авч болох уу?",
    "wordClass": "noun",
    "level": "B1"
  },
  {
    "german": "sagen",
    "mongolian": "хэлэх / ярих",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Kannst du mir das bitte noch einmal sagen?",
    "exampleMongolian": "Чи надад үүнийг дахиад нэг удаа хэлж өгөхгүй юу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "fragen",
    "mongolian": "асуух",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Darf ich Sie etwas fragen?",
    "exampleMongolian": "Би таниас нэг зүйл асууж болох уу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "antworten",
    "mongolian": "хариулах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Er antwortet nicht auf meine E-Mail.",
    "exampleMongolian": "Тэр миний цахим шууданд хариулахгүй байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "sehen",
    "mongolian": "харах / үзэх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich sehe dort drüben einen schönen Park.",
    "exampleMongolian": "Би тэнд нэг сайхан цэцэрлэгт хүрээлэн харж байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "hören",
    "mongolian": "сонсох",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Hörst du gerne Musik?",
    "exampleMongolian": "Чи хөгжим сонсох дуртай юу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "lesen",
    "mongolian": "унших",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Jeden Abend lese ich ein Buch.",
    "exampleMongolian": "Орой болгон би ном уншдаг.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "schreiben",
    "mongolian": "бичих",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich muss heute eine E-Mail schreiben.",
    "exampleMongolian": "Би өнөөдөр цахим шуудан бичих ёстой.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "spielen",
    "mongolian": "тоглох",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Die Kinder spielen im Garten.",
    "exampleMongolian": "Хүүхдүүд цэцэрлэгт тоглож байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "laufen",
    "mongolian": "гүйх / алхах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Wir laufen jeden Morgen im Park.",
    "exampleMongolian": "Бид өглөө болгон цэцэрлэгт хүрээлэнд гүйдэг.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "schlafen",
    "mongolian": "унтах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich schlafe jeden Tag acht Stunden.",
    "exampleMongolian": "Би өдөр бүр найман цаг унтдаг.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "stehen",
    "mongolian": "зогсох",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Er steht an der Bushaltestelle.",
    "exampleMongolian": "Тэр автобусны буудал дээр зогсож байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "sitzen",
    "mongolian": "суух",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Wir sitzen im Café.",
    "exampleMongolian": "Бид кафе дотор сууж байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "geben",
    "mongolian": "өгөх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Kannst du mir bitte das Salz geben?",
    "exampleMongolian": "Чи надад давс өгөөч?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "nehmen",
    "mongolian": "авах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich nehme eine Tasse Tee.",
    "exampleMongolian": "Би нэг аяга цай авъя.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "finden",
    "mongolian": "олох / санагдах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich kann meinen Schlüssel nicht finden.",
    "exampleMongolian": "Би түлхүүрээ олж чадахгүй байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "suchen",
    "mongolian": "хайх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Was suchst du in deiner Tasche?",
    "exampleMongolian": "Чи цүнхнээсээ юу хайж байгаа юм бэ?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "brauchen",
    "mongolian": "хэрэгтэй байх / шаардлагатай байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich brauche deine Hilfe.",
    "exampleMongolian": "Надад чиний тусламж хэрэгтэй байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "wollen",
    "mongolian": "хүсэх / ...маар байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich will am Wochenende Deutsch lernen.",
    "exampleMongolian": "Би амралтын өдрүүдээр герман хэл сурмаар байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "können",
    "mongolian": "чадах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Er kann sehr gut Klavier spielen.",
    "exampleMongolian": "Тэр төгөлдөр хуур маш сайн тоглож чаддаг.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "müssen",
    "mongolian": "ёстой / шаардлагатай байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich muss heute lange arbeiten.",
    "exampleMongolian": "Би өнөөдөр орой болтол ажиллах ёстой.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "mögen",
    "mongolian": "дуртай байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich mag Pizza und Pasta.",
    "exampleMongolian": "Би пицца болон пастанд дуртай.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "helfen",
    "mongolian": "туслах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Kannst du mir helfen?",
    "exampleMongolian": "Чи надад тусалж чадах уу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "lieben",
    "mongolian": "хайрлах / дурлах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich liebe dich.",
    "exampleMongolian": "Би чамд хайртай.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "leben",
    "mongolian": "амьдрах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Wir leben in Berlin.",
    "exampleMongolian": "Бид Берлинд амьдардаг.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "bleiben",
    "mongolian": "үлдэх / байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich bleibe heute zu Hause.",
    "exampleMongolian": "Би өнөөдөр гэртээ үлдэнэ.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "heißen",
    "mongolian": "гэж нэрлэгдэх / нэртэй байх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Wie heißen Sie?",
    "exampleMongolian": "Таныг хэн гэдэг вэ?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "öffnen",
    "mongolian": "нээх / онгойлгох",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Kannst du das Fenster öffnen?",
    "exampleMongolian": "Чи цонх онгойлгож чадах уу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "warten",
    "mongolian": "хүлээх",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Ich warte auf den Bus.",
    "exampleMongolian": "Би автобус хүлээж байна.",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "zeigen",
    "mongolian": "үзүүлэх / харуулах",
    "category": "Үйл үг (A1)",
    "exampleGerman": "Kannst du mir den Weg zeigen?",
    "exampleMongolian": "Чи надад замыг зааж өгч чадах уу?",
    "wordClass": "verb",
    "level": "A1"
  },
  {
    "german": "bezahlen",
    "mongolian": "төлөх / төлбөр хийх",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich möchte bitte bezahlen.",
    "exampleMongolian": "Би тооцоогоо хиймээр байна.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "bestellen",
    "mongolian": "захиалах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Wir möchten zwei Pizzen bestellen.",
    "exampleMongolian": "Бид хоёр пицца захиалмаар байна.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "reisen",
    "mongolian": "аялах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich reise gerne im Sommer.",
    "exampleMongolian": "Би зун аялах дуртай.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "besuchen",
    "mongolian": "зочлох / зочилж очих",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Am Wochenende besuche ich meine Großeltern.",
    "exampleMongolian": "Амралтын өдрүүдээр би өвөө эмээ дээрээ зочилно.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "treffen",
    "mongolian": "уулзах / учрах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Wir treffen uns morgen im Park.",
    "exampleMongolian": "Бид маргааш цэцэрлэгт хүрээлэнд уулзана.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "einkaufen",
    "mongolian": "худалдан авалт хийх / дэлгүүр хэсэх",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich muss heute im Supermarkt einkaufen.",
    "exampleMongolian": "Би өнөөдөр супермаркетад худалдан авалт хийх хэрэгтэй.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "kochen",
    "mongolian": "хоол хийх / чанах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Kochst du heute das Abendessen?",
    "exampleMongolian": "Чи өнөөдөр оройн хоол хийх үү?",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "waschen",
    "mongolian": "угаах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich muss meine Wäsche waschen.",
    "exampleMongolian": "Би хувцаснуудаа угаах хэрэгтэй.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "anrufen",
    "mongolian": "утсаар ярих / утасдах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Kannst du mich später anrufen?",
    "exampleMongolian": "Чи над руу дараа залгаж чадах уу?",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "aufstehen",
    "mongolian": "босох",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich stehe jeden Tag um 6 Uhr auf.",
    "exampleMongolian": "Би өдөр бүр 6 цагт босдог.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "vergessen",
    "mongolian": "мартах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich habe meinen Schlüssel vergessen.",
    "exampleMongolian": "Би түлхүүрээ мартчихаж.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "erklären",
    "mongolian": "тайлбарлах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Können Sie mir diese Grammatik erklären?",
    "exampleMongolian": "Та надад энэ дүрмийг тайлбарлаж өгөхгүй юу?",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "wiederholen",
    "mongolian": "давтах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Können Sie das bitte wiederholen?",
    "exampleMongolian": "Та үүнийг дахин давтаж хэлэхгүй юу?",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "üben",
    "mongolian": "дадлага хийх / дасгал хийх",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Ich muss jeden Tag Deutsch üben.",
    "exampleMongolian": "Би өдөр бүр герман хэлний дадлага хийх хэрэгтэй.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "gewinnen",
    "mongolian": "хожих / ялах",
    "category": "Үйл үг (A2)",
    "exampleGerman": "Unsere Mannschaft will das Spiel gewinnen.",
    "exampleMongolian": "Манай баг энэ тоглолтод хожихыг хүсэж байна.",
    "wordClass": "verb",
    "level": "A2"
  },
  {
    "german": "entscheiden",
    "mongolian": "шийдэх / шийдвэрлэх",
    "category": "Үйл үг (B1)",
    "exampleGerman": "Ich kann mich nicht entscheiden, welches Buch ich kaufen soll.",
    "exampleMongolian": "Би аль номыг худалдаж авахаа шийдэж чадахгүй байна.",
    "wordClass": "verb",
    "level": "B1"
  },
  {
    "german": "glücklich",
    "mongolian": "аз жаргалтай / баяртай",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Ich bin so glücklich, dich zu sehen.",
    "exampleMongolian": "Чамайг харсандаа би маш их баяртай байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "traurig",
    "mongolian": "гунигтай / уйтгартай",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Warum bist du so traurig?",
    "exampleMongolian": "Чи яагаад ийм гунигтай байгаа юм бэ?",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "müde",
    "mongolian": "ядарсан",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Nach der Arbeit bin ich immer sehr müde.",
    "exampleMongolian": "Ажлын дараа би үргэлж маш их ядардаг.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "hungrig",
    "mongolian": "өлссөн",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Wenn ich hungrig bin, kann ich nicht gut arbeiten.",
    "exampleMongolian": "Би өлссөн үедээ сайн ажиллаж чаддаггүй.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "krank",
    "mongolian": "өвчтэй",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Er kann heute nicht kommen, weil er krank ist.",
    "exampleMongolian": "Тэр өвчтэй байгаа учраас өнөөдөр ирж чадахгүй.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "gesund",
    "mongolian": "эрүүл / эрүүл чийрэг",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Obst und Gemüse sind sehr gesund.",
    "exampleMongolian": "Жимс, хүнсний ногоо нь эрүүл мэндэд маш тустай.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "lang",
    "mongolian": "урт",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Der Weg zum Bahnhof ist sehr lang.",
    "exampleMongolian": "Буудал руу очих зам маш урт.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "kurz",
    "mongolian": "богино",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Wir machen eine kurze Pause.",
    "exampleMongolian": "Бид богино хугацааны завсарлага авна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "schwer",
    "mongolian": "хүнд / хэцүү",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Diese Tasche ist sehr schwer.",
    "exampleMongolian": "Энэ цүнх маш хүнд байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "leicht",
    "mongolian": "хөнгөн / амархан",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Die Deutschprüfung war eigentlich ganz leicht.",
    "exampleMongolian": "Герман хэлний шалгалт уг нь нэлээд амархан байсан.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "voll",
    "mongolian": "дүүрэн",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Der Bus ist heute morgens immer voll.",
    "exampleMongolian": "Энэ автобус өглөө бүр дүүрэн байдаг.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "leer",
    "mongolian": "хоосон",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Meine Kaffeetasse ist schon wieder leer.",
    "exampleMongolian": "Миний кофены аяга дахиад л хоосон болчихлоо.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "sauber",
    "mongolian": "цэвэр / цэвэрхэн",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Das Zimmer ist jetzt sauber.",
    "exampleMongolian": "Өрөө одоо цэвэрхэн байна.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "schmutzig",
    "mongolian": "бохир / заваан",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Deine Schuhe sind sehr schmutzig.",
    "exampleMongolian": "Чиний гутал маш бохир байна.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "freundlich",
    "mongolian": "найрсаг / эелдэг",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Die Verkäuferin ist sehr freundlich.",
    "exampleMongolian": "Худалдагч маш найрсаг байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "nett",
    "mongolian": "найрсаг / сайхан сэтгэлтэй",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Herr Müller ist ein netter Mann.",
    "exampleMongolian": "Ноён Мюллер бол сайхан сэтгэлтэй хүн юм.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "laut",
    "mongolian": "чанга / шуугиантай",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Die Musik ist zu laut.",
    "exampleMongolian": "Хөгжим дэндүү чанга байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "leise",
    "mongolian": "аяархан / чимээгүй",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Kannst du bitte leise sprechen?",
    "exampleMongolian": "Чи аяархан ярьж болох уу?",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "hell",
    "mongolian": "гэрэлтэй / гэгээтэй",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Im Sommer ist es abends noch lange hell.",
    "exampleMongolian": "Зун оройдоо удаан хугацаанд гэгээтэй байдаг.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "dunkel",
    "mongolian": "харанхуй / бараан",
    "category": "Тэмдэг нэр (A2)",
    "exampleGerman": "Im Winter wird es schon früh dunkel.",
    "exampleMongolian": "Өвөл эрт харанхуй болдог.",
    "wordClass": "adjective",
    "level": "A2"
  },
  {
    "german": "billig",
    "mongolian": "хямд / хямдхан",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Das Ticket ist sehr billig.",
    "exampleMongolian": "Тасалбар маш хямдхан байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "wichtig",
    "mongolian": "чухал",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Diese Information ist sehr wichtig.",
    "exampleMongolian": "Энэ мэдээлэл маш чухал.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "richtig",
    "mongolian": "зөв",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Deine Antwort ist richtig.",
    "exampleMongolian": "Чиний хариулт зөв байна.",
    "wordClass": "adjective",
    "level": "A1"
  },
  {
    "german": "falsch",
    "mongolian": "буруу",
    "category": "Тэмдэг нэр (A1)",
    "exampleGerman": "Das ist leider die falsche Nummer.",
    "exampleMongolian": "Энэ харамсалтай нь буруу дугаар байна.",
    "wordClass": "adjective",
    "level": "A1"
  }
];
