// One-time batch job: fill in Mongolian glosses for dictionary entries that
// only have an English translation (the vocabeo-generated bulk). Writes
// frontend/src/mongolianGlosses.ts — a map keyed by "german|wordClass" that
// data.ts merges in at load time. Resumable: already-translated keys are
// skipped on re-run.
//
// Usage: npx tsx scripts/fillMongolianGlosses.ts
import 'dotenv/config';
import { GoogleGenAI } from '@google/genai';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

import { VOCABEO_VOCABULARY } from '../frontend/src/vocabeoVocabulary';
import { VOCABULARY_DATABASE } from '../frontend/src/data';
import { GENERATED_VOCABULARY } from '../frontend/src/generatedVocabulary';

const OUT_FILE = path.resolve(__dirname, '../frontend/src/mongolianGlosses.ts');
const BATCH_SIZE = 100;

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

function loadExisting(): Record<string, string> {
  if (!fs.existsSync(OUT_FILE)) return {};
  const src = fs.readFileSync(OUT_FILE, 'utf8');
  const m = src.match(/= (\{[\s\S]*\}) as const/);
  return m ? JSON.parse(m[1]) : {};
}

function save(glosses: Record<string, string>) {
  const body = JSON.stringify(glosses, null, 1);
  fs.writeFileSync(
    OUT_FILE,
    `// AUTO-GENERATED by scripts/fillMongolianGlosses.ts — do not edit by hand.\n` +
    `// Mongolian glosses for dictionary entries whose source only had English.\n` +
    `// Key: "<german>|<wordClass>".\n` +
    `export const MONGOLIAN_GLOSSES: Record<string, string> = ${body} as const;\n`
  );
}

const MODELS = ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.0-flash'];

async function generateWithRetry(contents: string) {
  let lastErr: unknown;
  for (let attempt = 0; attempt < 6; attempt++) {
    const model = MODELS[Math.min(attempt, MODELS.length - 1)];
    try {
      return await ai.models.generateContent({
        model,
        contents,
        config: { responseMimeType: 'application/json' },
      });
    } catch (e: any) {
      lastErr = e;
      const wait = 5000 * (attempt + 1);
      console.error(`attempt ${attempt + 1} (${model}) failed: ${e?.status ?? e?.message}; retrying in ${wait / 1000}s`);
      await new Promise(r => setTimeout(r, wait));
    }
  }
  throw lastErr;
}

async function main() {
  const all = [...VOCABULARY_DATABASE, ...GENERATED_VOCABULARY, ...VOCABEO_VOCABULARY];
  const glosses = loadExisting();
  const todo = all.filter(w =>
    (!w.mongolian || !w.mongolian.trim()) &&
    !glosses[`${w.german}|${w.wordClass ?? ''}`]
  );
  console.log(`missing Mongolian: ${todo.length} entries (already translated: ${Object.keys(glosses).length})`);

  for (let i = 0; i < todo.length; i += BATCH_SIZE) {
    const batch = todo.slice(i, i + BATCH_SIZE);
    const list = batch.map((w, j) =>
      `${j + 1}. ${w.article ? w.article + ' ' : ''}${w.german} (${w.wordClass ?? '?'}) = ${w.english ?? '?'}`
    ).join('\n');

    const res = await generateWithRetry(`You are translating a German learner's dictionary into Mongolian (Cyrillic script).
For each numbered German word below (its English meaning is given after "="), give a short
natural Mongolian gloss (1-4 words) that a Mongolian student of German would expect.
Return STRICT JSON only: an object whose keys are the item numbers as strings ("1", "2", ...)
and whose values are the Mongolian glosses. Every number must be present. No commentary.

${list}`);

    let obj: Record<string, string>;
    try {
      obj = JSON.parse(res.text ?? '{}');
    } catch {
      console.error(`batch ${i / BATCH_SIZE + 1}: bad JSON, skipping`);
      continue;
    }
    let filled = 0;
    batch.forEach((w, j) => {
      const mn = String(obj[String(j + 1)] ?? '').trim();
      // Reject glosses that are just the German/English word echoed back.
      if (mn && mn.toLowerCase() !== w.german.toLowerCase() && /[Ѐ-ӿ]/.test(mn)) {
        glosses[`${w.german}|${w.wordClass ?? ''}`] = mn;
        filled++;
      }
    });
    if (filled < batch.length) console.error(`batch ${i / BATCH_SIZE + 1}: ${batch.length - filled} items missing/invalid`);
    save(glosses); // checkpoint after every batch so the run is resumable
    console.log(`batch ${i / BATCH_SIZE + 1}/${Math.ceil(todo.length / BATCH_SIZE)} done (${Object.keys(glosses).length} total)`);
  }
  console.log('finished:', Object.keys(glosses).length, 'glosses written to', OUT_FILE);
}

main().catch(e => { console.error(e); process.exit(1); });
