// Seed list of common German words for the in-app dictionary (Browse).
// Only the German-side grammar facts are authored here (article, word class, CEFR level).
// The Mongolian meaning + example sentences are generated in generateVocabulary.ts.

import { WordClass, CEFRLevel } from '../frontend/src/types';

export interface SeedWord {
  german: string;
  article?: 'der' | 'die' | 'das';
  wordClass: WordClass;
  level: CEFRLevel;
}

export const SEED_WORDS: SeedWord[] = [
  // ---------- Nouns: food & drink (A1) ----------
  { german: 'Apfel', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Banane', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Brot', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Butter', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Käse', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Ei', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Fisch', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Fleisch', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Milch', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Kaffee', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Tee', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Saft', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Bier', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Wein', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Zucker', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Salz', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Suppe', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Kartoffel', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Gemüse', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Obst', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Kuchen', article: 'der', wordClass: 'noun', level: 'A2' },

  // ---------- Nouns: people & family (A1) ----------
  { german: 'Vater', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Mutter', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Bruder', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Schwester', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Eltern', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Sohn', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Tochter', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Junge', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Mädchen', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Mensch', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Lehrer', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Schüler', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Student', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Arzt', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Beruf', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Nachbar', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Gast', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Chef', article: 'der', wordClass: 'noun', level: 'B1' },
  { german: 'Kollege', article: 'der', wordClass: 'noun', level: 'B1' },

  // ---------- Nouns: home & city (A1–A2) ----------
  { german: 'Auto', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Bus', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Zug', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Fahrrad', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Straße', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Weg', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Dorf', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Wohnung', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Zimmer', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Küche', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Bett', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Stuhl', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Lampe', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Fenster', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Schrank', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Uhr', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Telefon', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Handy', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Computer', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Bank', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Supermarkt', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Markt', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Geschäft', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Restaurant', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Hotel', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Universität', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Büro', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Garten', article: 'der', wordClass: 'noun', level: 'A2' },

  // ---------- Nouns: nature, time & body (A1–A2) ----------
  { german: 'Baum', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Blume', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Hund', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Katze', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Vogel', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Tier', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Sonne', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Mond', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Himmel', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Wetter', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Regen', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Schnee', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Sommer', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Winter', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Abend', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Woche', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Monat', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Stunde', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Minute', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Sprache', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Wort', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Frage', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Antwort', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Hand', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Kopf', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Auge', article: 'das', wordClass: 'noun', level: 'A1' },
  { german: 'Fuß', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Herz', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Kleidung', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Schuh', article: 'der', wordClass: 'noun', level: 'A1' },
  { german: 'Jacke', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Farbe', article: 'die', wordClass: 'noun', level: 'A1' },
  { german: 'Reise', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Urlaub', article: 'der', wordClass: 'noun', level: 'A2' },
  { german: 'Welt', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Problem', article: 'das', wordClass: 'noun', level: 'A2' },
  { german: 'Idee', article: 'die', wordClass: 'noun', level: 'A2' },
  { german: 'Gesundheit', article: 'die', wordClass: 'noun', level: 'B1' },
  { german: 'Umwelt', article: 'die', wordClass: 'noun', level: 'B1' },
  { german: 'Erfahrung', article: 'die', wordClass: 'noun', level: 'B1' },
  { german: 'Meinung', article: 'die', wordClass: 'noun', level: 'B1' },
  { german: 'Termin', article: 'der', wordClass: 'noun', level: 'B1' },
  { german: 'Rechnung', article: 'die', wordClass: 'noun', level: 'B1' },

  // ---------- Verbs (A1) ----------
  { german: 'sagen', wordClass: 'verb', level: 'A1' },
  { german: 'fragen', wordClass: 'verb', level: 'A1' },
  { german: 'antworten', wordClass: 'verb', level: 'A1' },
  { german: 'sehen', wordClass: 'verb', level: 'A1' },
  { german: 'hören', wordClass: 'verb', level: 'A1' },
  { german: 'lesen', wordClass: 'verb', level: 'A1' },
  { german: 'schreiben', wordClass: 'verb', level: 'A1' },
  { german: 'spielen', wordClass: 'verb', level: 'A1' },
  { german: 'laufen', wordClass: 'verb', level: 'A1' },
  { german: 'schlafen', wordClass: 'verb', level: 'A1' },
  { german: 'stehen', wordClass: 'verb', level: 'A1' },
  { german: 'sitzen', wordClass: 'verb', level: 'A1' },
  { german: 'geben', wordClass: 'verb', level: 'A1' },
  { german: 'nehmen', wordClass: 'verb', level: 'A1' },
  { german: 'finden', wordClass: 'verb', level: 'A1' },
  { german: 'suchen', wordClass: 'verb', level: 'A1' },
  { german: 'brauchen', wordClass: 'verb', level: 'A1' },
  { german: 'wollen', wordClass: 'verb', level: 'A1' },
  { german: 'können', wordClass: 'verb', level: 'A1' },
  { german: 'müssen', wordClass: 'verb', level: 'A1' },
  { german: 'mögen', wordClass: 'verb', level: 'A1' },
  { german: 'helfen', wordClass: 'verb', level: 'A1' },
  { german: 'lieben', wordClass: 'verb', level: 'A1' },
  { german: 'leben', wordClass: 'verb', level: 'A1' },
  { german: 'bleiben', wordClass: 'verb', level: 'A1' },
  { german: 'heißen', wordClass: 'verb', level: 'A1' },
  { german: 'öffnen', wordClass: 'verb', level: 'A1' },
  { german: 'warten', wordClass: 'verb', level: 'A1' },
  { german: 'zeigen', wordClass: 'verb', level: 'A1' },

  // ---------- Verbs (A2–B1) ----------
  { german: 'bezahlen', wordClass: 'verb', level: 'A2' },
  { german: 'bestellen', wordClass: 'verb', level: 'A2' },
  { german: 'reisen', wordClass: 'verb', level: 'A2' },
  { german: 'besuchen', wordClass: 'verb', level: 'A2' },
  { german: 'treffen', wordClass: 'verb', level: 'A2' },
  { german: 'einkaufen', wordClass: 'verb', level: 'A2' },
  { german: 'kochen', wordClass: 'verb', level: 'A2' },
  { german: 'waschen', wordClass: 'verb', level: 'A2' },
  { german: 'anrufen', wordClass: 'verb', level: 'A2' },
  { german: 'aufstehen', wordClass: 'verb', level: 'A2' },
  { german: 'vergessen', wordClass: 'verb', level: 'A2' },
  { german: 'erklären', wordClass: 'verb', level: 'A2' },
  { german: 'wiederholen', wordClass: 'verb', level: 'A2' },
  { german: 'üben', wordClass: 'verb', level: 'A2' },
  { german: 'gewinnen', wordClass: 'verb', level: 'A2' },
  { german: 'entscheiden', wordClass: 'verb', level: 'B1' },
  { german: 'empfehlen', wordClass: 'verb', level: 'B1' },
  { german: 'vorschlagen', wordClass: 'verb', level: 'B1' },
  { german: 'beschreiben', wordClass: 'verb', level: 'B1' },
  { german: 'vergleichen', wordClass: 'verb', level: 'B1' },
  { german: 'bedeuten', wordClass: 'verb', level: 'B1' },
  { german: 'verbessern', wordClass: 'verb', level: 'B1' },
  { german: 'sich freuen', wordClass: 'verb', level: 'B1' },
  { german: 'sich erinnern', wordClass: 'verb', level: 'B1' },

  // ---------- Adjectives (A1) ----------
  { german: 'jung', wordClass: 'adjective', level: 'A1' },
  { german: 'warm', wordClass: 'adjective', level: 'A1' },
  { german: 'kalt', wordClass: 'adjective', level: 'A1' },
  { german: 'heiß', wordClass: 'adjective', level: 'A1' },
  { german: 'glücklich', wordClass: 'adjective', level: 'A1' },
  { german: 'traurig', wordClass: 'adjective', level: 'A1' },
  { german: 'müde', wordClass: 'adjective', level: 'A1' },
  { german: 'hungrig', wordClass: 'adjective', level: 'A1' },
  { german: 'krank', wordClass: 'adjective', level: 'A1' },
  { german: 'gesund', wordClass: 'adjective', level: 'A2' },
  { german: 'lang', wordClass: 'adjective', level: 'A1' },
  { german: 'kurz', wordClass: 'adjective', level: 'A1' },
  { german: 'schwer', wordClass: 'adjective', level: 'A1' },
  { german: 'leicht', wordClass: 'adjective', level: 'A1' },
  { german: 'voll', wordClass: 'adjective', level: 'A1' },
  { german: 'leer', wordClass: 'adjective', level: 'A2' },
  { german: 'sauber', wordClass: 'adjective', level: 'A2' },
  { german: 'schmutzig', wordClass: 'adjective', level: 'A2' },
  { german: 'freundlich', wordClass: 'adjective', level: 'A1' },
  { german: 'nett', wordClass: 'adjective', level: 'A1' },
  { german: 'laut', wordClass: 'adjective', level: 'A1' },
  { german: 'leise', wordClass: 'adjective', level: 'A2' },
  { german: 'hell', wordClass: 'adjective', level: 'A2' },
  { german: 'dunkel', wordClass: 'adjective', level: 'A2' },
  { german: 'billig', wordClass: 'adjective', level: 'A1' },
  { german: 'wichtig', wordClass: 'adjective', level: 'A1' },
  { german: 'richtig', wordClass: 'adjective', level: 'A1' },
  { german: 'falsch', wordClass: 'adjective', level: 'A1' },
  { german: 'einfach', wordClass: 'adjective', level: 'A1' },
  { german: 'schwierig', wordClass: 'adjective', level: 'A2' },
  { german: 'interessant', wordClass: 'adjective', level: 'A1' },
  { german: 'langweilig', wordClass: 'adjective', level: 'A2' },
  { german: 'möglich', wordClass: 'adjective', level: 'A2' },
  { german: 'gefährlich', wordClass: 'adjective', level: 'B1' },
  { german: 'pünktlich', wordClass: 'adjective', level: 'B1' },
  { german: 'erfolgreich', wordClass: 'adjective', level: 'B1' },

  // ---------- Adverbs (A1–B1) ----------
  { german: 'hier', wordClass: 'adverb', level: 'A1' },
  { german: 'dort', wordClass: 'adverb', level: 'A1' },
  { german: 'oben', wordClass: 'adverb', level: 'A2' },
  { german: 'unten', wordClass: 'adverb', level: 'A2' },
  { german: 'links', wordClass: 'adverb', level: 'A1' },
  { german: 'rechts', wordClass: 'adverb', level: 'A1' },
  { german: 'gern', wordClass: 'adverb', level: 'A1' },
  { german: 'sehr', wordClass: 'adverb', level: 'A1' },
  { german: 'auch', wordClass: 'adverb', level: 'A1' },
  { german: 'nur', wordClass: 'adverb', level: 'A1' },
  { german: 'schon', wordClass: 'adverb', level: 'A1' },
  { german: 'noch', wordClass: 'adverb', level: 'A1' },
  { german: 'wieder', wordClass: 'adverb', level: 'A1' },
  { german: 'oft', wordClass: 'adverb', level: 'A1' },
  { german: 'manchmal', wordClass: 'adverb', level: 'A1' },
  { german: 'selten', wordClass: 'adverb', level: 'A2' },
  { german: 'nie', wordClass: 'adverb', level: 'A1' },
  { german: 'bald', wordClass: 'adverb', level: 'A2' },
  { german: 'früh', wordClass: 'adverb', level: 'A1' },
  { german: 'spät', wordClass: 'adverb', level: 'A1' },
  { german: 'zusammen', wordClass: 'adverb', level: 'A1' },
  { german: 'allein', wordClass: 'adverb', level: 'A2' },
  { german: 'trotzdem', wordClass: 'adverb', level: 'B1' },
  { german: 'deshalb', wordClass: 'adverb', level: 'B1' },
  { german: 'plötzlich', wordClass: 'adverb', level: 'B1' },
  { german: 'endlich', wordClass: 'adverb', level: 'B1' },
  { german: 'wahrscheinlich', wordClass: 'adverb', level: 'B1' },
  { german: 'normalerweise', wordClass: 'adverb', level: 'B1' },
  { german: 'besonders', wordClass: 'adverb', level: 'B1' },

  // ---------- Prepositions (A1–A2) ----------
  { german: 'in', wordClass: 'preposition', level: 'A1' },
  { german: 'auf', wordClass: 'preposition', level: 'A1' },
  { german: 'mit', wordClass: 'preposition', level: 'A1' },
  { german: 'für', wordClass: 'preposition', level: 'A1' },
  { german: 'ohne', wordClass: 'preposition', level: 'A1' },
  { german: 'zu', wordClass: 'preposition', level: 'A1' },
  { german: 'von', wordClass: 'preposition', level: 'A1' },
  { german: 'bei', wordClass: 'preposition', level: 'A2' },
  { german: 'nach', wordClass: 'preposition', level: 'A2' },
  { german: 'über', wordClass: 'preposition', level: 'A2' },
  { german: 'unter', wordClass: 'preposition', level: 'A2' },
  { german: 'zwischen', wordClass: 'preposition', level: 'A2' },

  // ---------- Useful phrases (A1) ----------
  { german: 'Guten Morgen', wordClass: 'phrase', level: 'A1' },
  { german: 'Guten Tag', wordClass: 'phrase', level: 'A1' },
  { german: 'Guten Abend', wordClass: 'phrase', level: 'A1' },
  { german: 'Gute Nacht', wordClass: 'phrase', level: 'A1' },
  { german: 'Auf Wiedersehen', wordClass: 'phrase', level: 'A1' },
  { german: 'Tschüss', wordClass: 'phrase', level: 'A1' },
  { german: 'Wie geht es dir?', wordClass: 'phrase', level: 'A1' },
  { german: 'Bis bald', wordClass: 'phrase', level: 'A1' },
  { german: 'Viel Glück', wordClass: 'phrase', level: 'A2' },
  { german: 'Alles Gute', wordClass: 'phrase', level: 'A2' },
  { german: 'Es tut mir leid', wordClass: 'phrase', level: 'A1' },
  { german: 'Herzlich willkommen', wordClass: 'phrase', level: 'A2' },
];
